// Code generated by Demesne. DO NOT EDIT.

package authz

import (
	"context"
	"encoding/json"
	"net/http"

	demesne "github.com/eidestudio/demesne"
)

type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

var claimsContract = []string{"member_id", "sub", "tenant_id", "workspace_id"}

type Claims struct {
	MemberID    string
	Sub         string
	TenantID    string
	WorkspaceID string
	Extra       map[string]string
}

func (c Claims) values() map[string]string {
	m := map[string]string{}
	if c.MemberID != "" {
		m["member_id"] = c.MemberID
	}
	if c.Sub != "" {
		m["sub"] = c.Sub
	}
	if c.TenantID != "" {
		m["tenant_id"] = c.TenantID
	}
	if c.WorkspaceID != "" {
		m["workspace_id"] = c.WorkspaceID
	}
	return m
}

func (c Claims) Mint() (string, error) {
	return demesne.MintClaimsValuesWithExtra(claimsContract, c.values(), c.Extra)
}

const ConnectionRole = "authenticated"
const claimsGUC = "request.jwt.claims"

func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

type workspaceAccess struct{}

var Workspace = workspaceAccess{}

func (workspaceAccess) CanView(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM workspaces WHERE id = $1)", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

func (workspaceAccess) CanEdit(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM workspaces WHERE id = $1 AND (auth.is_root((current_setting('request.jwt.claims', true)::json ->> 'sub')) OR (tenant_id = (current_setting('request.jwt.claims', true)::json ->> 'tenant_id') AND (auth.is_tenant_staff((current_setting('request.jwt.claims', true)::json ->> 'sub'), tenant_id) OR id = (current_setting('request.jwt.claims', true)::json ->> 'workspace_id') AND auth.is_ws_editor((current_setting('request.jwt.claims', true)::json ->> 'sub'), tenant_id, id)))))", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

func (workspaceAccess) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM workspaces WHERE ($1::text IS NULL OR id::text > $1::text) ORDER BY id::text LIMIT $2", after, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

func (workspaceAccess) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM workspaces WHERE id = ANY($1)", ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

type docAccess struct{}

var Doc = docAccess{}

func (docAccess) CanView(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM docs WHERE id = $1)", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

func (docAccess) CanEdit(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM docs WHERE id = $1 AND ((auth.is_root((current_setting('request.jwt.claims', true)::json ->> 'sub')) AND (current_setting('request.jwt.claims', true)::json ->> 'workspace_id') IS NULL) OR (tenant_id = (current_setting('request.jwt.claims', true)::json ->> 'tenant_id') AND workspace_id = (current_setting('request.jwt.claims', true)::json ->> 'workspace_id') AND (owner_id = (current_setting('request.jwt.claims', true)::json ->> 'member_id') OR auth.doc_acl_grants((current_setting('request.jwt.claims', true)::json ->> 'member_id'), docs.id, 'write')))))", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

func (docAccess) CanPublish(held demesne.EffectivePerms) Decision {
	if !held.Holds("docs:publish") {
		return Deny
	}
	return Allow
}

func (docAccess) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM docs WHERE ($1::text IS NULL OR id::text > $1::text) ORDER BY id::text LIMIT $2", after, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

func (docAccess) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM docs WHERE id = ANY($1)", ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

var holdsResolver = &demesne.HoldsResolver{
	Assignments: "role_grants",
	KindCol:     "grantee_kind",
	KindVal:     "staff",
	SubjectCol:  "grantee_id",
	ScopeCols:   []string{"tenant_id", "workspace_id"},
	RevokedCol:  "revoked_at",
	RoleCol:     "role_id",
	RolesTable:  "roles",
	RolesID:     "id",
	KeyCol:      "key",
	PermsCol:    "",
	Vocab: &demesne.Vocabulary{
		Name:        "staff",
		Permissions: []string{"docs:read", "docs:write", "docs:publish"},
		Presets: []*demesne.Preset{
			{Name: "ws_viewer", Level: "workspace", Star: false, Set: []string{"docs:read"}},
			{Name: "ws_editor", Level: "workspace", Star: false, Set: []string{"ws_viewer", "docs:write", "docs:publish"}},
			{Name: "tenant_owner", Level: "tenant", Star: true, Set: []string{}},
		},
		Rank: []string{"tenant_owner", "ws_editor", "ws_viewer"},
	},
}

const AssignmentsSQL = "SELECT ra.tenant_id, ra.workspace_id, r.key FROM role_grants ra JOIN roles r ON r.id = ra.role_id WHERE ra.grantee_kind = 'staff' AND ra.grantee_id = $1 AND ra.revoked_at IS NULL"

func ResolveHeld(assignments []demesne.RoleAssignment, scope []string) (demesne.EffectivePerms, error) {
	return holdsResolver.Resolve(assignments, scope)
}

func Holds(ctx context.Context, q demesne.Querier, principalID string, scope []string) (demesne.EffectivePerms, error) {
	rows, err := q.QueryContext(ctx, AssignmentsSQL, principalID)
	if err != nil {
		return demesne.EffectivePerms{}, err
	}
	defer rows.Close()
	var assignments []demesne.RoleAssignment
	for rows.Next() {
		a := demesne.RoleAssignment{Scope: make([]string, 2)}
		if err := rows.Scan(&a.Scope[0], &a.Scope[1], &a.RoleKey); err != nil {
			return demesne.EffectivePerms{}, err
		}
		assignments = append(assignments, a)
	}
	if err := rows.Err(); err != nil {
		return demesne.EffectivePerms{}, err
	}
	return ResolveHeld(assignments, scope)
}

func Check(ctx context.Context, q demesne.Querier, object, verb, id string) (Decision, error) {
	switch object + "." + verb {
	case "workspace.view":
		return Workspace.CanView(ctx, q, id)
	case "workspace.edit":
		return Workspace.CanEdit(ctx, q, id)
	case "doc.view":
		return Doc.CanView(ctx, q, id)
	case "doc.edit":
		return Doc.CanEdit(ctx, q, id)
	default:
		return NotGoverned, nil
	}
}

func CheckHandler(q demesne.Querier) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		d, err := Check(r.Context(), q, r.FormValue("object"), r.FormValue("verb"), r.FormValue("id"))
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]string{"decision": d.String()})
	}
}
