// Code generated by Demesne from the authorization spec. DO NOT EDIT.
//
// The typed app surface: Claims + session, per-object Can<Verb>, scoped query
// builders, the holds-resolver, a reusable Check, and an HTTP check endpoint. Imports
// the demesne engine for the shared composition rules; everything runs under the
// caller's claims so the DB decides. Adapt a connection with demesne.FromSQL
// (database/sql) or github.com/eidestudio/demesne/pgx.FromPgx (pgx).

package authz

import (
	"context"
	"encoding/json"
	"net/http"

	demesne "github.com/eidestudio/demesne"
)

// Decision is the engine's authorization decision tri-state, re-exported so callers
// need not import the engine directly.
type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

// claimsContract is the spec's claim key set (byte-sorted) — the keys Claims mints.
var claimsContract = []string{"member_id", "sub", "tenant_id", "workspace_id"}

// Claims is the typed claims contract — one field per key. A zero-value field is
// omitted from the minted blob. Extra carries deployment-specific, NON-contract
// claims (a derived discriminator, a secrets-DB key) the spec does not model; they
// are merged in without contract validation (EID-371 §4.3).
type Claims struct {
	MemberID    string
	Sub         string
	TenantID    string
	WorkspaceID string
	Extra       map[string]string
}

func (c Claims) values() map[string]string {
	m := map[string]string{}
	if c.MemberID != "" {
		m["member_id"] = c.MemberID
	}
	if c.Sub != "" {
		m["sub"] = c.Sub
	}
	if c.TenantID != "" {
		m["tenant_id"] = c.TenantID
	}
	if c.WorkspaceID != "" {
		m["workspace_id"] = c.WorkspaceID
	}
	return m
}

// Mint renders the deterministic claims blob (sorted keys) to install in the GUC.
func (c Claims) Mint() (string, error) {
	return demesne.MintClaimsValuesWithExtra(claimsContract, c.values(), c.Extra)
}

// The RLS connection role + claims GUC the session assumes (spec-declared, defaulted).
const ConnectionRole = "authenticated"
const claimsGUC = "request.jwt.claims"

// SetRoleSQL assumes the RLS connection role so policies evaluate; local scopes it to
// the current transaction.
func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

// ClaimsSetSQL installs the minted claims blob ($1) into the GUC the policies read.
func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

// SessionSetupSQL is the WithRLS envelope: assume the role, then install the claims. Run in
// order at the top of an RLS transaction; the SECOND statement binds the Mint() result to $1.
func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

// Workspace is the typed access surface for the "workspace" object (table workspaces, pk id).
type workspaceAccess struct{}

var Workspace = workspaceAccess{}

// CanView reports whether the caller can SEE the workspace row (its read policy). Run under the caller's claims + RLS role.
func (workspaceAccess) CanView(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM workspaces WHERE id = $1)", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

// CanEdit reports whether the caller can EDIT the workspace row (visible AND its update policy). Run under the caller's claims + RLS role.
func (workspaceAccess) CanEdit(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM workspaces WHERE id = $1 AND (auth.is_root((current_setting('request.jwt.claims', true)::json ->> 'sub')) OR (tenant_id = (current_setting('request.jwt.claims', true)::json ->> 'tenant_id') AND (auth.is_tenant_staff((current_setting('request.jwt.claims', true)::json ->> 'sub'), tenant_id) OR id = (current_setting('request.jwt.claims', true)::json ->> 'workspace_id') AND auth.is_ws_editor((current_setting('request.jwt.claims', true)::json ->> 'sub'), tenant_id, id)))))", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

// ListResources returns a keyset page of the workspace rows the caller can SEE.
// after is the last PK of the previous page (nil for the first); limit is the page size.
func (workspaceAccess) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM workspaces WHERE ($1::text IS NULL OR id::text > $1::text) ORDER BY id::text LIMIT $2", after, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// CheckMany returns the subset of ids the caller can SEE (one round-trip).
func (workspaceAccess) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM workspaces WHERE id = ANY($1)", ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// Doc is the typed access surface for the "doc" object (table docs, pk id).
type docAccess struct{}

var Doc = docAccess{}

// CanView reports whether the caller can SEE the doc row (its read policy). Run under the caller's claims + RLS role.
func (docAccess) CanView(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM docs WHERE id = $1)", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

// CanEdit reports whether the caller can EDIT the doc row (visible AND its update policy). Run under the caller's claims + RLS role.
func (docAccess) CanEdit(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM docs WHERE id = $1 AND ((auth.is_root((current_setting('request.jwt.claims', true)::json ->> 'sub')) AND (current_setting('request.jwt.claims', true)::json ->> 'workspace_id') IS NULL) OR (tenant_id = (current_setting('request.jwt.claims', true)::json ->> 'tenant_id') AND workspace_id = (current_setting('request.jwt.claims', true)::json ->> 'workspace_id') AND (owner_id = (current_setting('request.jwt.claims', true)::json ->> 'member_id') OR auth.doc_acl_grants((current_setting('request.jwt.claims', true)::json ->> 'member_id'), docs.id, 'write')))))", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

// CanPublish reports whether the caller's held permissions admit "publish" (a @pdp verb — no row
// predicate). Resolve `held` with Holds(...).
func (docAccess) CanPublish(held demesne.EffectivePerms) Decision {
	if !held.Holds("docs:publish") {
		return Deny
	}
	return Allow
}

// ListResources returns a keyset page of the doc rows the caller can SEE.
// after is the last PK of the previous page (nil for the first); limit is the page size.
func (docAccess) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM docs WHERE ($1::text IS NULL OR id::text > $1::text) ORDER BY id::text LIMIT $2", after, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// CheckMany returns the subset of ids the caller can SEE (one round-trip).
func (docAccess) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT id FROM docs WHERE id = ANY($1)", ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// holdsResolver is the "staff" rolestore projection the engine resolves over.
var holdsResolver = &demesne.HoldsResolver{
	Assignments: "role_grants",
	KindCol:     "grantee_kind",
	KindVal:     "staff",
	SubjectCol:  "grantee_id",
	ScopeCols:   []string{"tenant_id", "workspace_id"},
	RevokedCol:  "revoked_at",
	RoleCol:     "role_id",
	RolesTable:  "roles",
	RolesID:     "id",
	KeyCol:      "key",
	PermsCol:    "",
	Vocab: &demesne.Vocabulary{
		Name:        "staff",
		Permissions: []string{"docs:read", "docs:write", "docs:publish"},
		Presets: []*demesne.Preset{
			{Name: "ws_viewer", Level: "workspace", Star: false, Set: []string{"docs:read"}},
			{Name: "ws_editor", Level: "workspace", Star: false, Set: []string{"ws_viewer", "docs:write", "docs:publish"}},
			{Name: "tenant_owner", Level: "tenant", Star: true, Set: []string{}},
		},
		Rank: []string{"tenant_owner", "ws_editor", "ws_viewer"},
	},
}

// AssignmentsSQL is the GENERIC active-assignment read ($1 = principal id). To apply
// adopter admission policy the generic read omits (disabled roles, RP-scoped grants, a
// role allowlist), copy it, add your WHERE conjuncts, scan into []demesne.RoleAssignment,
// and call ResolveHeld — the seam Holds deliberately leaves open (EID-371 §4.2).
const AssignmentsSQL = "SELECT ra.tenant_id, ra.workspace_id, r.key FROM role_grants ra JOIN roles r ON r.id = ra.role_id WHERE ra.grantee_kind = 'staff' AND ra.grantee_id = $1 AND ra.revoked_at IS NULL"

// ResolveHeld folds active-assignment rows into the effective permission set at a
// scope (the scope-containment match + union). Pair it with your own filtered read.
func ResolveHeld(assignments []demesne.RoleAssignment, scope []string) (demesne.EffectivePerms, error) {
	return holdsResolver.Resolve(assignments, scope)
}

// Holds resolves a principal's effective permissions at a scope via the GENERIC read.
// For adopter admission filters use the AssignmentsSQL + ResolveHeld seam instead.
// scope is the scope-column values root->leaf; an empty string leaves a level unpinned.
func Holds(ctx context.Context, q demesne.Querier, principalID string, scope []string) (demesne.EffectivePerms, error) {
	rows, err := q.QueryContext(ctx, AssignmentsSQL, principalID)
	if err != nil {
		return demesne.EffectivePerms{}, err
	}
	defer rows.Close()
	var assignments []demesne.RoleAssignment
	for rows.Next() {
		a := demesne.RoleAssignment{Scope: make([]string, 2)}
		if err := rows.Scan(&a.Scope[0], &a.Scope[1], &a.RoleKey); err != nil {
			return demesne.EffectivePerms{}, err
		}
		assignments = append(assignments, a)
	}
	if err := rows.Err(); err != nil {
		return demesne.EffectivePerms{}, err
	}
	return ResolveHeld(assignments, scope)
}

// Check dispatches a row read/edit check by object + verb (the dynamic, transport-free
// surface). An unknown object/verb returns NotGoverned. @pdp verbs are not dispatchable
// by id — use the typed Can<Verb>(held) + Holds.
func Check(ctx context.Context, q demesne.Querier, object, verb, id string) (Decision, error) {
	switch object + "." + verb {
	case "workspace.view":
		return Workspace.CanView(ctx, q, id)
	case "workspace.edit":
		return Workspace.CanEdit(ctx, q, id)
	case "doc.view":
		return Doc.CanView(ctx, q, id)
	case "doc.edit":
		return Doc.CanEdit(ctx, q, id)
	default:
		return NotGoverned, nil
	}
}

// CheckHandler answers the app-level read/edit check over Check:
//
//	?object=<o>&verb=<v>&id=<id>  ->  {"decision":"allow|deny|ungoverned"}
//
// Pass a Querier already bound to the request's session (role + claims set).
func CheckHandler(q demesne.Querier) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		d, err := Check(r.Context(), q, r.FormValue("object"), r.FormValue("verb"), r.FormValue("id"))
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]string{"decision": d.String()})
	}
}
