package demesne

import (
	"strings"
	"testing"
)

func TestRenderClaimsContractTS(t *testing.T) {
	s := mustSpec(t, runtimeSpec)
	got, err := s.RenderClaimsContractTS("Contract")
	if err != nil {
		t.Fatalf("RenderClaimsContractTS: %v", err)
	}
	want := "// Code generated by Demesne. DO NOT EDIT.\n" +
		`export const Contract: string[] = ["customer_id","project_id","sub","tenant_id"];` + "\n"
	if got != want {
		t.Errorf("RenderClaimsContractTS:\n got: %q\nwant: %q", got, want)
	}
}

func TestPDPRenderTS(t *testing.T) {
	s := mustSpec(t, runtimeSpec)
	pdps, err := s.EmitPDP()
	if err != nil {
		t.Fatalf("EmitPDP: %v", err)
	}
	got := pdps["admin"].RenderTS("Policy")
	want := "// Code generated by Demesne. DO NOT EDIT.\n" +
		`export const Policy: Record<string, string> = {"records.v1.RecordsService/UpdateRecord":"content:write"};` + "\n"
	if got != want {
		t.Errorf("PDP.RenderTS:\n got: %q\nwant: %q", got, want)
	}
}

func TestEmitTS_ReadSurfacesOnly(t *testing.T) {
	s := mustSpec(t, runtimeSpec)
	got, err := s.EmitTS()
	if err != nil {
		t.Fatalf("EmitTS: %v", err)
	}
	mustContain(t, got, []string{
		`import type { AppObjectSurface, Claims, Pdp } from "@demesne/runtime";`,
		"export const claims: Claims = {",
		`"setting": "request.jwt.claims"`,
		`"role": "authenticated"`,
		`"key": "customer_id"`,
		"export const appSurface: AppObjectSurface[] = [",
		`"table": "records"`,
		"export const pdp: Record<string, Pdp> = {",
		`"records.v1.RecordsService/UpdateRecord": "content:write"`,
	})
	for _, absent := range []string{"holdsResolver", "roleAssignment", "export const grants", "resourceAccess"} {
		if strings.Contains(got, absent) {
			t.Errorf("EmitTS(read-only) should not emit %q:\n%s", absent, got)
		}
	}
}

func TestEmitTS_HoldsAndRoleAssignment(t *testing.T) {
	s, err := Parse(holdsSpec)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	got, err := s.EmitTS()
	if err != nil {
		t.Fatalf("EmitTS: %v", err)
	}
	mustContain(t, got, []string{
		"export const holdsResolver: HoldsResolver = {",
		`"assignments": "role_assignments"`,
		`"permsCol": "perms"`,
		`"tenant_id"`,
		`"team_id"`,
		`"vocab": {`,
		`"name": "roles"`,
		"export const roleAssignment: RoleAssignmentSurface = {",
		`"rolesId": "id"`,
	})
}

func TestEmitTS_Grants(t *testing.T) {
	s := mustSpec(t, fullGrantSpec)
	got, err := s.EmitTS()
	if err != nil {
		t.Fatalf("EmitTS: %v", err)
	}
	mustContain(t, got, []string{
		"export const grants: Record<string, GrantSurface> = {",
		`"impersonation": {`,
		`"activeCol": "revoked_at"`,
		`"expiresCol": "expires_at"`,
		`"reason"`,
	})
}

func TestEmitTS_ResourceAccess(t *testing.T) {
	s := mustSpec(t, adminOwnerSpec)
	got, err := s.EmitTS()
	if err != nil {
		t.Fatalf("EmitTS: %v", err)
	}
	mustContain(t, got, []string{
		"export const resourceAccess: Record<string, ResourceAccessSurface> = {",
		`"aclTable": "resource_acl"`,
		`"discrimCol": "resource_type"`,
		`"discrimVal": "record"`,
		`"accessorFn": "auth.records_accessors"`,
	})
}

func mustContain(t *testing.T, got string, wants []string) {
	t.Helper()
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("emitted TS missing %q in:\n%s", w, got)
		}
	}
}
