package demesne

import (
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// Framework codegen (EID-289; hardened in EID-371 from the foir adoption stress test) — the
// compiler→framework leap. The other emitters produce SQL (the moat) + plain-data
// projections; this one produces the TYPED Go an app is built on: a `Claims` struct, the
// session envelope, per-object/per-verb `Can<Verb>` methods, scoped query builders, a
// holds-resolver with an adopter seam, a reusable dynamic `Check`, and an HTTP endpoint.
//
// The generated package IMPORTS the demesne engine for the shared runtime (Decision /
// ComposeCan / the holds-resolver / the Querier surface) and bakes only the per-spec data +
// typed wrappers — the same split as the TypeScript target. So the engine owns the
// composition rules; the generated code is a thin, typed, spec-shaped surface over it.
//
// The DB surface (`demesne.Querier`) lives in the engine, so the generated package references
// it directly (no per-package `Querier` to collide with an adopter's types) and one adapter
// serves every generated package: `demesne.FromSQL` for database/sql, `demesne/pgx.FromPgx`
// for pgx. Everything runs under the caller's minted claims + RLS role (equal by delegation).

// EmitFramework renders the spec as a self-describing typed Go package (DO NOT EDIT) in the
// given package name (default "authz"). It imports github.com/eidestudio/demesne and is
// gofmt'd. Composite-PK objects (no single-column row identity) get no Can/list surface and
// are listed in a banner (EID-371 §4.1).
func (s *Spec) EmitFramework(pkg string) (string, error) {
	if pkg == "" {
		pkg = "authz"
	}
	contract, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	surf, err := s.EmitAppSurface() // already omits composite-PK (non-point-checkable) objects
	if err != nil {
		return "", err
	}

	skipped := s.compositePKObjects()
	orphanPDP := s.orphanPDPVerbs()

	g := &fwGen{pkg: pkg, spec: s}
	g.header()
	g.preamble()
	g.claims(contract)
	g.banner(skipped)
	g.pdpBanner(orphanPDP)
	for _, o := range surf.Objects {
		obj := s.objectByName(o.Object)
		if obj == nil {
			continue
		}
		g.object(o, obj)
	}
	for _, rs := range s.RoleStores {
		suffix := ""
		if len(s.RoleStores) > 1 {
			suffix = goExport(rs.Name)
		}
		if err := g.holds(rs, suffix); err != nil {
			return "", err
		}
	}
	g.checkFunc()
	g.checkHandler()

	// gofmt the output — guarantees canonical formatting AND parses it (a syntax error in
	// the generator surfaces here, not at the adopter's compile).
	formatted, err := format.Source([]byte(g.b.String()))
	if err != nil {
		return "", fmt.Errorf("EmitFramework: generated code does not parse: %w", err)
	}
	return string(formatted), nil
}

// compositePKObjects lists the objects with no single-column row identity (EID-371 §4.1).
func (s *Spec) compositePKObjects() []*Object {
	var skipped []*Object
	for _, o := range s.Objects {
		if !o.pointCheckable() {
			skipped = append(skipped, o)
		}
	}
	return skipped
}

// orphanPDPVerbs lists @pdp verbs (object.verb) whose required permission no rolestore
// vocabulary covers — their Can<Verb>(held) is emitted, but no generated Holds resolver can
// produce `held` for them (EID-371 §4.7).
func (s *Spec) orphanPDPVerbs() []string {
	covered := map[string]bool{}
	for _, rs := range s.RoleStores {
		if v, err := s.rolestoreVocab(rs); err == nil && v != nil {
			for _, p := range v.Permissions {
				covered[p] = true
			}
		}
	}
	var orphan []string
	for _, o := range s.Objects {
		if !o.pointCheckable() {
			continue
		}
		for _, pm := range o.Perms {
			if !containsStr(pm.Layers, "pdp") {
				continue
			}
			for _, tok := range pm.Expr {
				if tok.Ident != "" && !covered[tok.Ident] {
					orphan = append(orphan, fmt.Sprintf("%s.%s (needs %q)", o.Name, pm.Verb, tok.Ident))
				}
			}
		}
	}
	return orphan
}

type fwGen struct {
	pkg    string
	spec   *Spec
	b      strings.Builder
	checks []fwCheck // (object, verb, method) row checks — for the reusable Check / HTTP dispatcher
}

type fwCheck struct{ object, verb, method string }

func (g *fwGen) header() {
	g.b.WriteString("// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	g.b.WriteString("//\n// The typed app surface: Claims + session, per-object Can<Verb>, scoped query\n")
	g.b.WriteString("// builders, the holds-resolver, a reusable Check, and an HTTP check endpoint. Imports\n")
	g.b.WriteString("// the demesne engine for the shared composition rules; everything runs under the\n")
	g.b.WriteString("// caller's claims so the DB decides. Adapt a connection with demesne.FromSQL\n")
	g.b.WriteString("// (database/sql) or github.com/eidestudio/demesne/pgx.FromPgx (pgx).\n\n")
	fmt.Fprintf(&g.b, "package %s\n\n", g.pkg)
	g.b.WriteString("import (\n")
	g.b.WriteString("\t\"context\"\n")
	g.b.WriteString("\t\"encoding/json\"\n")
	g.b.WriteString("\t\"net/http\"\n\n")
	g.b.WriteString("\tdemesne \"github.com/eidestudio/demesne\"\n")
	g.b.WriteString(")\n\n")
}

func (g *fwGen) preamble() {
	g.b.WriteString(`// Decision is the engine's authorization decision tri-state, re-exported so callers
// need not import the engine directly.
type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

`)
}

func (g *fwGen) claims(contract []string) {
	setting, _ := g.spec.claimSetting()
	role := g.spec.claimRole()

	g.b.WriteString("// claimsContract is the spec's claim key set (byte-sorted) — the keys Claims mints.\n")
	fmt.Fprintf(&g.b, "var claimsContract = %s\n\n", goStrSlice(contract))

	g.b.WriteString("// Claims is the typed claims contract — one field per key. A zero-value field is\n")
	g.b.WriteString("// omitted from the minted blob. Extra carries deployment-specific, NON-contract\n")
	g.b.WriteString("// claims (a derived discriminator, a secrets-DB key) the spec does not model; they\n")
	g.b.WriteString("// are merged in without contract validation (EID-371 §4.3).\n")
	g.b.WriteString("type Claims struct {\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "\t%s string\n", goExport(k))
	}
	g.b.WriteString("\tExtra map[string]string\n")
	g.b.WriteString("}\n\n")

	g.b.WriteString("func (c Claims) values() map[string]string {\n")
	g.b.WriteString("\tm := map[string]string{}\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "\tif c.%s != \"\" {\n\t\tm[%q] = c.%s\n\t}\n", goExport(k), k, goExport(k))
	}
	g.b.WriteString("\treturn m\n}\n\n")

	g.b.WriteString("// Mint renders the deterministic claims blob (sorted keys) to install in the GUC.\n")
	g.b.WriteString("func (c Claims) Mint() (string, error) {\n")
	g.b.WriteString("\treturn demesne.MintClaimsValuesWithExtra(claimsContract, c.values(), c.Extra)\n}\n\n")

	fmt.Fprintf(&g.b, "// The RLS connection role + claims GUC the session assumes (spec-declared, defaulted).\n")
	fmt.Fprintf(&g.b, "const ConnectionRole = %q\n", role)
	fmt.Fprintf(&g.b, "const claimsGUC = %q\n\n", setting)

	g.b.WriteString(`// SetRoleSQL assumes the RLS connection role so policies evaluate; local scopes it to
// the current transaction.
func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

// ClaimsSetSQL installs the minted claims blob ($1) into the GUC the policies read.
func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

// SessionSetupSQL is the WithRLS envelope: assume the role, then install the claims. Run in
// order at the top of an RLS transaction; the SECOND statement binds the Mint() result to $1.
func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

`)
}

// banner lists the objects with no single-column row identity (composite PK) — they get no
// Can/ListResources/CheckMany (EID-371 §4.1).
func (g *fwGen) banner(skipped []*Object) {
	if len(skipped) == 0 {
		return
	}
	g.b.WriteString("// NOTE: these objects declare a composite primary key — there is no single-column row\n")
	g.b.WriteString("// identity to point-check, so NO Can / ListResources / CheckMany is generated for them\n")
	g.b.WriteString("// (EID-371 §4.1). Check access to such rows via your own predicate or a related object:\n")
	for _, o := range skipped {
		fmt.Fprintf(&g.b, "//   - %s (table %s, pk %s)\n", o.Name, o.Table, strings.Join(o.PKCols, ", "))
	}
	g.b.WriteString("\n")
}

// pdpBanner warns about @pdp verbs whose required permission no rolestore vocabulary covers —
// their Can<Verb>(held) is emitted, but no generated Holds can produce `held` for them, so
// the caller must resolve it themselves or add a rolestore (EID-371 §4.7).
func (g *fwGen) pdpBanner(orphan []string) {
	if len(orphan) == 0 {
		return
	}
	g.b.WriteString("// NOTE: these @pdp verbs need a permission no rolestore vocabulary covers, so NO generated\n")
	g.b.WriteString("// Holds resolver can produce their `held` input — resolve it yourself, or add a rolestore\n")
	g.b.WriteString("// for the permission's vocabulary (EID-371 §4.7):\n")
	for _, v := range orphan {
		fmt.Fprintf(&g.b, "//   - %s\n", v)
	}
	g.b.WriteString("\n")
}

// object emits one object's typed access surface: its Can<Verb> methods (read / edit / @pdp),
// the scoped query builders, and registers the row checks for Check / CheckHandler.
func (g *fwGen) object(o AppObjectSurface, obj *Object) {
	recv := unexport(o.Object) + "Access"
	exp := goExport(o.Object)

	fmt.Fprintf(&g.b, "// %s is the typed access surface for the %q object (table %s, pk %s).\n", exp, o.Object, o.Table, o.PK)
	fmt.Fprintf(&g.b, "type %s struct{}\n\n", recv)
	fmt.Fprintf(&g.b, "var %s = %s{}\n\n", exp, recv)

	for _, pm := range obj.Perms {
		verb := goExport(pm.Verb)
		switch {
		case containsStr(pm.Layers, "pdp"):
			g.pdpCan(recv, pm)
		case pm.Maps == "select":
			g.rowCan(recv, exp, o.Object, pm.Verb, "Can"+verb, o.CheckSQL(),
				fmt.Sprintf("can SEE the %s row (its read policy)", o.Object))
		case pm.Maps == "update":
			if o.EditCheckSQL == "" {
				continue
			}
			g.rowCan(recv, exp, o.Object, pm.Verb, "Can"+verb, o.EditCheckSQL,
				fmt.Sprintf("can EDIT the %s row (visible AND its update policy)", o.Object))
		default:
			// insert/delete and unmapped verbs have no row point-check; skipped.
		}
	}

	// Scoped query builders: keyset list (fast-path when flat-eligible) + batch check.
	listSQL := o.ListResourcesSQL()
	fast := ""
	if o.FlatListFn != "" {
		listSQL = o.ListResourcesFastSQL()
		fast = " (drives from the materialized flat so the keyset LIMIT pushes down)"
	}
	fmt.Fprintf(&g.b, "// ListResources returns a keyset page of the %s rows the caller can SEE%s.\n", o.Object, fast)
	fmt.Fprintf(&g.b, "// after is the last PK of the previous page (nil for the first); limit is the page size.\n")
	fmt.Fprintf(&g.b, "func (%s) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {\n", recv)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, after, limit)\n", goRawString(listSQL))
	g.scanIDs()

	fmt.Fprintf(&g.b, "// CheckMany returns the subset of ids the caller can SEE (one round-trip).\n")
	fmt.Fprintf(&g.b, "func (%s) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {\n", recv)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, ids)\n", goRawString(o.CheckManySQL()))
	g.scanIDs()
}

// scanIDs writes the rows→[]string scan loop shared by ListResources and CheckMany.
func (g *fwGen) scanIDs() {
	g.b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar out []string\n\tfor rows.Next() {\n\t\tvar id string\n\t\tif err := rows.Scan(&id); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tout = append(out, id)\n\t}\n\treturn out, rows.Err()\n}\n\n")
}

// rowCan emits a point-check Can method (read or edit) and registers it for Check / CheckHandler.
func (g *fwGen) rowCan(recv, exp, object, verb, method, sql, doc string) {
	fmt.Fprintf(&g.b, "// %s reports whether the caller %s. Run under the caller's claims + RLS role.\n", method, doc)
	fmt.Fprintf(&g.b, "func (%s) %s(ctx context.Context, q demesne.Querier, id string) (Decision, error) {\n", recv, method)
	g.b.WriteString("\tvar ok bool\n")
	fmt.Fprintf(&g.b, "\tif err := q.QueryRowContext(ctx, %s, id).Scan(&ok); err != nil {\n", goRawString(sql))
	g.b.WriteString("\t\treturn Deny, err\n\t}\n")
	g.b.WriteString("\treturn demesne.ComposeCan(true, ok, demesne.NotGoverned), nil\n}\n\n")
	g.checks = append(g.checks, fwCheck{object: object, verb: verb, method: exp + "." + method})
}

// pdpCan emits a @pdp verb check: the caller's held permissions decide (no row predicate).
func (g *fwGen) pdpCan(recv string, pm *Perm) {
	var perms []string
	for _, t := range pm.Expr {
		if t.Ident != "" {
			perms = append(perms, t.Ident)
		}
	}
	method := "Can" + goExport(pm.Verb)
	fmt.Fprintf(&g.b, "// %s reports whether the caller's held permissions admit %q (a @pdp verb — no row\n", method, pm.Verb)
	fmt.Fprintf(&g.b, "// predicate). Resolve `held` with Holds(...).\n")
	fmt.Fprintf(&g.b, "func (%s) %s(held demesne.EffectivePerms) Decision {\n", recv, method)
	for _, p := range perms {
		fmt.Fprintf(&g.b, "\tif !held.Holds(%q) {\n\t\treturn Deny\n\t}\n", p)
	}
	g.b.WriteString("\treturn Allow\n}\n\n")
}

// holds emits one rolestore's resolver: the baked projection, the raw read as a const + a
// ResolveHeld seam (so adopters can run their OWN admission-filtered read — EID-371 §4.2),
// and a bundled Holds for the simple case. Names are suffixed per rolestore when >1 (§4.7).
func (g *fwGen) holds(rs *RoleStore, suffix string) error {
	r, err := g.spec.HoldsResolver(rs.Name)
	if err != nil {
		return err
	}
	fmt.Fprintf(&g.b, "// holdsResolver%s is the %q rolestore projection the engine resolves over.\n", suffix, rs.Name)
	fmt.Fprintf(&g.b, "var holdsResolver%s = %s\n\n", suffix, g.resolverLit(r))

	fmt.Fprintf(&g.b, "// AssignmentsSQL%s is the GENERIC active-assignment read ($1 = principal id). To apply\n", suffix)
	fmt.Fprintf(&g.b, "// adopter admission policy the generic read omits (disabled roles, RP-scoped grants, a\n")
	fmt.Fprintf(&g.b, "// role allowlist), copy it, add your WHERE conjuncts, scan into []demesne.RoleAssignment,\n")
	fmt.Fprintf(&g.b, "// and call ResolveHeld%s — the seam Holds%s deliberately leaves open (EID-371 §4.2).\n", suffix, suffix)
	fmt.Fprintf(&g.b, "const AssignmentsSQL%s = %s\n\n", suffix, goRawString(r.AssignmentsSQL()))

	fmt.Fprintf(&g.b, "// ResolveHeld%s folds active-assignment rows into the effective permission set at a\n", suffix)
	fmt.Fprintf(&g.b, "// scope (the scope-containment match + union). Pair it with your own filtered read.\n")
	fmt.Fprintf(&g.b, "func ResolveHeld%s(assignments []demesne.RoleAssignment, scope []string) (demesne.EffectivePerms, error) {\n", suffix)
	fmt.Fprintf(&g.b, "\treturn holdsResolver%s.Resolve(assignments, scope)\n}\n\n", suffix)

	matComment := ""
	if r.PermsCol != "" {
		matComment = " (the materialized permissions column is scanned as []string — use a driver\n" +
			"// that scans text[] into []string, e.g. pgx)"
	}
	fmt.Fprintf(&g.b, "// Holds%s resolves a principal's effective permissions at a scope via the GENERIC read%s.\n", suffix, matComment)
	fmt.Fprintf(&g.b, "// For adopter admission filters use the AssignmentsSQL%s + ResolveHeld%s seam instead.\n", suffix, suffix)
	g.b.WriteString("// scope is the scope-column values root->leaf; an empty string leaves a level unpinned.\n")
	fmt.Fprintf(&g.b, "func Holds%s(ctx context.Context, q demesne.Querier, principalID string, scope []string) (demesne.EffectivePerms, error) {\n", suffix)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, AssignmentsSQL%s, principalID)\n", suffix)
	g.b.WriteString("\tif err != nil {\n\t\treturn demesne.EffectivePerms{}, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar assignments []demesne.RoleAssignment\n")
	g.b.WriteString("\tfor rows.Next() {\n")
	fmt.Fprintf(&g.b, "\t\ta := demesne.RoleAssignment{Scope: make([]string, %d)}\n", len(r.ScopeCols))
	dest := make([]string, 0, len(r.ScopeCols)+2)
	for i := range r.ScopeCols {
		dest = append(dest, fmt.Sprintf("&a.Scope[%d]", i))
	}
	dest = append(dest, "&a.RoleKey")
	if r.PermsCol != "" {
		dest = append(dest, "&a.Permissions")
	}
	fmt.Fprintf(&g.b, "\t\tif err := rows.Scan(%s); err != nil {\n", strings.Join(dest, ", "))
	g.b.WriteString("\t\t\treturn demesne.EffectivePerms{}, err\n\t\t}\n")
	g.b.WriteString("\t\tassignments = append(assignments, a)\n\t}\n")
	g.b.WriteString("\tif err := rows.Err(); err != nil {\n\t\treturn demesne.EffectivePerms{}, err\n\t}\n")
	fmt.Fprintf(&g.b, "\treturn ResolveHeld%s(assignments, scope)\n}\n\n", suffix)
	return nil
}

// checkFunc emits a reusable dynamic dispatcher over the row Can<Verb> checks, for callers
// keyed by an object/verb STRING (a Connect RPC, a gateway) — the transport-free core
// CheckHandler wraps (EID-371 §4.4). An unknown object/verb is NotGoverned (no claim).
func (g *fwGen) checkFunc() {
	g.b.WriteString("// Check dispatches a row read/edit check by object + verb (the dynamic, transport-free\n")
	g.b.WriteString("// surface). An unknown object/verb returns NotGoverned. @pdp verbs are not dispatchable\n")
	g.b.WriteString("// by id — use the typed Can<Verb>(held) + Holds.\n")
	g.b.WriteString("func Check(ctx context.Context, q demesne.Querier, object, verb, id string) (Decision, error) {\n")
	g.b.WriteString("\tswitch object + \".\" + verb {\n")
	for _, c := range g.checks {
		fmt.Fprintf(&g.b, "\tcase %q:\n\t\treturn %s(ctx, q, id)\n", c.object+"."+c.verb, c.method)
	}
	g.b.WriteString("\tdefault:\n\t\treturn NotGoverned, nil\n\t}\n}\n\n")
}

// checkHandler emits a ready-to-mount HTTP endpoint over Check:
// ?object=&verb=&id= → {"decision":"allow|deny|ungoverned"}. Pass a Querier already bound to
// the request's session (role + claims set).
func (g *fwGen) checkHandler() {
	g.b.WriteString("// CheckHandler answers the app-level read/edit check over Check:\n")
	g.b.WriteString("//   ?object=<o>&verb=<v>&id=<id>  ->  {\"decision\":\"allow|deny|ungoverned\"}\n")
	g.b.WriteString("// Pass a Querier already bound to the request's session (role + claims set).\n")
	g.b.WriteString("func CheckHandler(q demesne.Querier) http.HandlerFunc {\n")
	g.b.WriteString("\treturn func(w http.ResponseWriter, r *http.Request) {\n")
	g.b.WriteString("\t\td, err := Check(r.Context(), q, r.FormValue(\"object\"), r.FormValue(\"verb\"), r.FormValue(\"id\"))\n")
	g.b.WriteString("\t\tif err != nil {\n\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n\t\t\treturn\n\t\t}\n")
	g.b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	g.b.WriteString("\t\t_ = json.NewEncoder(w).Encode(map[string]string{\"decision\": d.String()})\n")
	g.b.WriteString("\t}\n}\n")
}

// --- Go-literal helpers -----------------------------------------------------------

// resolverLit renders a *HoldsResolver as a Go composite literal (incl. its Vocab).
func (g *fwGen) resolverLit(r *HoldsResolver) string {
	var b strings.Builder
	b.WriteString("&demesne.HoldsResolver{\n")
	fmt.Fprintf(&b, "\tAssignments: %q,\n", r.Assignments)
	fmt.Fprintf(&b, "\tKindCol:     %q,\n", r.KindCol)
	fmt.Fprintf(&b, "\tKindVal:     %q,\n", r.KindVal)
	fmt.Fprintf(&b, "\tSubjectCol:  %q,\n", r.SubjectCol)
	fmt.Fprintf(&b, "\tScopeCols:   %s,\n", goStrSlice(r.ScopeCols))
	fmt.Fprintf(&b, "\tRevokedCol:  %q,\n", r.RevokedCol)
	fmt.Fprintf(&b, "\tRoleCol:     %q,\n", r.RoleCol)
	fmt.Fprintf(&b, "\tRolesTable:  %q,\n", r.RolesTable)
	fmt.Fprintf(&b, "\tRolesID:     %q,\n", r.RolesID)
	fmt.Fprintf(&b, "\tKeyCol:      %q,\n", r.KeyCol)
	fmt.Fprintf(&b, "\tPermsCol:    %q,\n", r.PermsCol)
	fmt.Fprintf(&b, "\tVocab:       %s,\n", g.vocabLit(r.Vocab))
	b.WriteString("}")
	return b.String()
}

func (g *fwGen) vocabLit(v *Vocabulary) string {
	if v == nil {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("&demesne.Vocabulary{\n")
	fmt.Fprintf(&b, "\t\tName:        %q,\n", v.Name)
	fmt.Fprintf(&b, "\t\tPermissions: %s,\n", goStrSlice(v.Permissions))
	if len(v.Presets) > 0 {
		b.WriteString("\t\tPresets: []*demesne.Preset{\n")
		for _, p := range v.Presets {
			fmt.Fprintf(&b, "\t\t\t{Name: %q, Level: %q, Star: %t, Set: %s},\n", p.Name, p.Level, p.Star, goStrSlice(p.Set))
		}
		b.WriteString("\t\t},\n")
	}
	fmt.Fprintf(&b, "\t\tRank:        %s,\n", goStrSlice(v.Rank))
	b.WriteString("\t}")
	return b.String()
}

// goStrSlice renders a []string as a Go composite literal (nil/empty → []string{}).
func goStrSlice(ss []string) string {
	if len(ss) == 0 {
		return "[]string{}"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// goRawString renders s as a Go double-quoted string literal (SQL has no backticks/newlines).
func goRawString(s string) string { return fmt.Sprintf("%q", s) }

// goExport converts a snake/kebab/colon identifier to an exported Go name (id -> ID).
func goExport(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ':' || r == '.' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		if up := strings.ToUpper(p); commonInitialisms[up] {
			parts[i] = up
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// unexport lowercases an exported name for a private receiver, handling a leading initialism
// run correctly: "APIKeys" -> "apiKeys", "ID" -> "id", "Doc" -> "doc" (EID-371 §4.8).
func unexport(s string) string {
	r := []rune(goExport(s))
	if len(r) == 0 {
		return ""
	}
	i := 0
	for i < len(r) && unicode.IsUpper(r[i]) {
		i++
	}
	if i == len(r) { // all-caps (e.g. "ID")
		return strings.ToLower(string(r))
	}
	if i > 1 { // a leading initialism run; its last upper starts the next word ("APIKeys")
		i--
	}
	return strings.ToLower(string(r[:i])) + string(r[i:])
}

var commonInitialisms = map[string]bool{"ID": true, "URL": true, "API": true, "SQL": true, "UID": true, "ACL": true, "PK": true}

func containsStr(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}
