package demesne

import (
	"fmt"
	"strings"
)

// Supabase deployment profile (EID-339) — the deployment-side analogue of an emit target.
// Where an emit target (e.g. EID-338's TypeScript) renders the generated authorization
// SURFACE for a language, a profile renders the deployment GLUE for a platform. Demesne's
// generated RLS already reads `current_setting('request.jwt.claims', true)::json ->> '<key>'`
// and policies are `TO authenticated` — which are EXACTLY Supabase's defaults — so the only
// missing piece on Supabase is getting the spec's claims-contract keys INTO that GUC.
//
// On Supabase the JWT is minted by GoTrue and exposed to Postgres (via PostgREST) as the
// `request.jwt.claims` GUC. Custom, app-controlled claims live in a user's `app_metadata`.
// This profile emits the **custom access-token hook** — a Postgres function GoTrue calls at
// token-mint time — that LIFTS each Demesne contract key from `app_metadata` to a top-level
// claim, so the generated RLS predicates read them unchanged. Nothing about the emitted RLS
// changes; the profile is pure deployment wiring, derived from the spec's claims contract.
//
// The adopter populates `app_metadata` with the contract keys via BuildClaims + Supabase's
// admin API (see the deploy guide); the connection role stays `authenticated` (non-BYPASSRLS),
// and `service_role` (BYPASSRLS) is reserved for trusted server paths — `demesne check`
// verifies the role is not BYPASSRLS.

// supabaseHookFn is the generated hook's function name (in schema public, where Supabase
// auth hooks live and `supabase_auth_admin` can reach them).
const supabaseHookFn = "demesne_access_token_hook"

// supabaseGUC is the only claims GUC Supabase's PostgREST populates; the profile requires
// the spec to use it (the engine's default), since a custom setting would never be set.
const supabaseGUC = "request.jwt.claims"

// EmitSupabaseProfile renders the Supabase deployment profile for the spec: the custom
// access-token hook (lifting every claims-contract key from app_metadata into the JWT) plus
// the grant/revoke statements Supabase requires for an auth hook. Errors when the spec
// declares a non-default claims GUC (Supabase can only populate request.jwt.claims).
func (s *Spec) EmitSupabaseProfile() (string, error) {
	setting, cast := s.claimSetting()
	if setting != supabaseGUC {
		return "", fmt.Errorf(
			"EmitSupabaseProfile: spec claims setting is %q, but Supabase's PostgREST populates only %q — remove the custom `claims via` setting for the Supabase profile",
			setting, supabaseGUC)
	}
	keys, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	role := s.claimRole()

	var b strings.Builder
	b.WriteString("-- Code generated by Demesne — Supabase deployment profile. DO NOT EDIT.\n")
	b.WriteString("--\n")
	b.WriteString("-- Register this function as the \"Custom Access Token\" auth hook (Dashboard -> Auth ->\n")
	b.WriteString("-- Hooks, or config.toml [auth.hook.custom_access_token]). It lifts each Demesne\n")
	b.WriteString("-- claims-contract key from a user's app_metadata into the JWT, so the generated RLS\n")
	fmt.Fprintf(&b, "-- policies -- which read current_setting('%s', true)::%s ->> '<key>' -- see them.\n", setting, cast)
	b.WriteString("-- Populate app_metadata with these keys via BuildClaims + the Supabase admin API.\n")
	b.WriteString("--\n")
	fmt.Fprintf(&b, "-- The RLS connection role is %q (non-BYPASSRLS -- the moat). service_role (BYPASSRLS)\n", role)
	b.WriteString("-- must be used ONLY for trusted server-side / bootstrap paths, NEVER the request path:\n")
	b.WriteString("-- a request-path query under service_role silently bypasses every policy.\n\n")

	fmt.Fprintf(&b, "create or replace function public.%s(event jsonb)\n", supabaseHookFn)
	b.WriteString("returns jsonb\n")
	b.WriteString("language plpgsql\n")
	b.WriteString("stable\n")
	b.WriteString("as $$\n")
	b.WriteString("declare\n")
	b.WriteString("  claims jsonb;\n")
	b.WriteString("  meta jsonb;\n")
	b.WriteString("begin\n")
	b.WriteString("  claims := event->'claims';\n")
	b.WriteString("  meta := coalesce(claims->'app_metadata', '{}'::jsonb);\n")
	b.WriteString("  -- one lift per Demesne claims-contract key (app_metadata -> top-level claim):\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "  if meta ? '%s' then claims := jsonb_set(claims, '{%s}', meta->'%s'); end if;\n", k, k, k)
	}
	b.WriteString("  event := jsonb_set(event, '{claims}', claims);\n")
	b.WriteString("  return event;\n")
	b.WriteString("end;\n")
	b.WriteString("$$;\n\n")

	fmt.Fprintf(&b, "grant execute on function public.%s to supabase_auth_admin;\n", supabaseHookFn)
	b.WriteString("grant usage on schema public to supabase_auth_admin;\n")
	fmt.Fprintf(&b, "revoke execute on function public.%s from authenticated, anon, public;\n", supabaseHookFn)

	return b.String(), nil
}
