package demesne

import (
	"fmt"
	"strings"
)

func (s *Spec) RenderClaimsContractGo(varName string) (string, error) {
	keys, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	b.WriteString("// The JWT claims contract: every scope column (per non-virtual topology\n")
	b.WriteString("// level) + every subject identity key. WithRLS / session minting must set\n")
	b.WriteString("// these; no RLS predicate may reference a key outside this set (V5).\n")
	fmt.Fprintf(&b, "var %s = []string{\n", varName)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q,\n", k)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func (s *Spec) RenderClaimsContractEntriesGo(varName string) (string, error) {
	entries, err := s.ClaimsContractEntries()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	b.WriteString("// The STRUCTURED JWT claims contract: each key + where its value comes from\n")
	b.WriteString("// (a topology level's scope id and/or a subject's identity). A derived\n")
	b.WriteString("// claims-builder maps a principal onto these without hand-mapping field names.\n")
	b.WriteString("type DemesneClaimEntry struct {\n")
	b.WriteString("\tKey      string\n")
	b.WriteString("\tLevel    string\n")
	b.WriteString("\tSubjects []string\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "var %s = []DemesneClaimEntry{\n", varName)
	for _, e := range entries {
		fmt.Fprintf(&b, "\t{Key: %q, Level: %q, Subjects: %s},\n", e.Key, e.Level, renderStringSlice(e.Subjects))
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func renderStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", s)
	}
	b.WriteString("}")
	return b.String()
}
