package demesne

import (
	"fmt"
	"strings"
)

// Claims-contract emitter (RFC §6.1). The topology + subjects own the JWT claims
// contract end-to-end; this renders it as a generated Go artifact (the canonical
// key set WithRLS / session minting must provide). Phase B has the live
// BuildRLSClaims consume this; Phase A's oracle asserts the live minting covers
// every key and no RLS predicate references a key outside it.

// RenderClaimsContractGo emits a deterministic, sorted Go declaration of the
// claims contract for the given var name.
func (s *Spec) RenderClaimsContractGo(varName string) (string, error) {
	keys, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	b.WriteString("// The JWT claims contract: every scope column (per non-virtual topology\n")
	b.WriteString("// level) + every subject identity key. WithRLS / session minting must set\n")
	b.WriteString("// these; no RLS predicate may reference a key outside this set (V5).\n")
	fmt.Fprintf(&b, "var %s = []string{\n", varName)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q,\n", k)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// RenderClaimsContractEntriesGo emits the STRUCTURED claims contract (EID-334):
// each key plus its source — the topology level whose scope id feeds it, and the
// subjects whose `identifies` feeds it. It is the machine-readable provenance a
// derived claims-builder consumes (the data BuildClaims uses at runtime), rendered
// as a generated artifact for adopters who codegen the mapping. The DemesneClaimEntry
// type it references mirrors the engine's ClaimEntry; emitting the type alongside
// keeps the artifact self-contained.
func (s *Spec) RenderClaimsContractEntriesGo(varName string) (string, error) {
	entries, err := s.ClaimsContractEntries()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	b.WriteString("// The STRUCTURED JWT claims contract: each key + where its value comes from\n")
	b.WriteString("// (a topology level's scope id and/or a subject's identity). A derived\n")
	b.WriteString("// claims-builder maps a principal onto these without hand-mapping field names.\n")
	b.WriteString("type DemesneClaimEntry struct {\n")
	b.WriteString("\tKey      string\n")
	b.WriteString("\tLevel    string\n")
	b.WriteString("\tSubjects []string\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "var %s = []DemesneClaimEntry{\n", varName)
	for _, e := range entries {
		fmt.Fprintf(&b, "\t{Key: %q, Level: %q, Subjects: %s},\n", e.Key, e.Level, renderStringSlice(e.Subjects))
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// renderStringSlice renders a []string as a Go composite literal (nil → "nil").
func renderStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", s)
	}
	b.WriteString("}")
	return b.String()
}
