package demesne

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEmitFrameworkTS_Shape(t *testing.T) {
	s := loadExample(t)
	src, err := s.EmitFrameworkTS()
	if err != nil {
		t.Fatalf("EmitFrameworkTS: %v", err)
	}
	for _, want := range []string{
		"// Code generated by Demesne. DO NOT EDIT.",
		`import { Decision, composeCan, mintClaimsValuesWithExtra, resolve, resolveRoles } from "@foir/demesne";`,
		`import type { EffectivePerms, EffectiveRoles, HoldsResolver, RoleAssignment } from "@foir/demesne";`,
		"export { Decision };",
		"export interface Claims {",
		"export function mint(c: Claims): string {",
		"return mintClaimsValuesWithExtra(claimsContract, values, c.extra);",
		"export function sessionSetupSQL(local: boolean): [string, string] {",
		"export interface Querier {",
		"export const doc = {",
		"async canView(q: Querier, id: string): Promise<Decision> {",
		"async canEdit(q: Querier, id: string): Promise<Decision> {",
		"canPublish(held: EffectivePerms): Decision {",
		`if (!held.holds("docs:publish")) return Decision.Deny;`,
		"async listResources(q: Querier, after: string | null, limit: number): Promise<string[]> {",
		"async checkMany(q: Querier, ids: string[]): Promise<string[]> {",
		"export const holdsResolver: HoldsResolver = {",
		"export const assignmentsSQL = ",
		"export function resolveHeld(assignments: RoleAssignment[], scope: string[]): EffectivePerms {",
		"export async function holds(q: Querier, principalId: string, scope: string[]): Promise<EffectivePerms> {",
		"export function resolveHeldRoles(assignments: RoleAssignment[], scope: string[]): EffectiveRoles {",
		"export async function holdsRoles(q: Querier, principalId: string, scope: string[]): Promise<EffectiveRoles> {",
		"export function roleTiers(held: EffectiveRoles) {",
		`platformAdmin: held.holds("platform_admin"),`,
		`tenantOwner: held.holds("tenant_owner"),`,
		"export async function check(q: Querier, object: string, verb: string, id: string): Promise<Decision> {",
		`case "doc.view":`,
		`case "workspace.edit":`,
		"export function checkHandler(q: Querier): (req: Request) => Promise<Response> {",
		"composeCan(true, Boolean(rows[0]?.exists), Decision.NotGoverned)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated TS framework missing %q", want)
		}
	}
}

func TestEmitFrameworkTS_CompositePKSkip(t *testing.T) {
	const spec = `
topology { level tenant }
vocabulary v { permission a:read }
subject u { anchor tenant reach self identifies sub roles none }
object acl { table resource_acl pk (resource_id, principal_id, access) scoped tenant relation o: u via principal_id permission view = o @rls maps select }
object note { table notes scoped tenant relation o: u via owner_id permission view = o @rls maps select }
`
	s := mustValidSpec(t, spec)
	src, err := s.EmitFrameworkTS()
	if err != nil {
		t.Fatalf("EmitFrameworkTS: %v", err)
	}
	if strings.Contains(src, "export const acl =") || strings.Contains(src, `"acl.view"`) {
		t.Errorf("composite-PK object 'acl' should have NO can surface:\n%s", src)
	}
	for _, want := range []string{
		"composite primary key",
		"acl (table resource_acl, pk resource_id, principal_id, access)",
		"export const note = {",
		"async canView(q: Querier, id: string): Promise<Decision> {",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated TS framework missing %q", want)
		}
	}
}

func TestEmitFrameworkTS_OrphanPDPBanner(t *testing.T) {
	const spec = `
topology { level tenant level project parent tenant }

vocabulary staff {
  permission docs:read
  permission docs:publish
  preset viewer @ tenant = docs:read
  preset admin  @ tenant = *
  rank admin > viewer
}
vocabulary ops {
  permission jobs:run
}

rolestore staff { assignments staff_grants kind grantee_kind = "staff" subject grantee_id scope tenant_id project_id rolejoin role_id roles id key revoked revoked_at }

subject staffer { anchor tenant reach descendants identifies sub   roles configurable staff binds admin }
subject opser   { anchor tenant reach descendants identifies opsid roles configurable ops   binds owner }

object doc {
  table docs
  scoped tenant > project
  relation admin: staffer via role
  relation owner: opser   via owner_id
  permission view = admin + owner @rls maps select
  permission run  = jobs:run @pdp
}
`
	s := mustValidSpec(t, spec)
	src, err := s.EmitFrameworkTS()
	if err != nil {
		t.Fatalf("EmitFrameworkTS: %v", err)
	}
	for _, want := range []string{
		"These @pdp verbs need a permission no rolestore vocabulary covers",
		`doc.run (needs "jobs:run")`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("orphan @pdp banner missing %q:\n%s", want, src)
		}
	}
}

func TestEmitFrameworkTS_MultiRolestore(t *testing.T) {
	const spec = `
topology { level tenant level project parent tenant }

vocabulary staff {
  permission docs:read
  permission docs:publish
  preset viewer @ tenant = docs:read
  preset admin  @ tenant = *
  rank admin > viewer
}
vocabulary ops {
  permission jobs:run
  permission jobs:cancel
  preset operator @ tenant = jobs:run
  preset lead     @ tenant = *
  rank lead > operator
}

rolestore staff { assignments staff_grants kind grantee_kind = "staff" subject grantee_id scope tenant_id project_id rolejoin role_id roles id key revoked revoked_at }
rolestore ops   { assignments ops_grants   kind grantee_kind = "ops"   subject grantee_id scope tenant_id project_id rolejoin role_id roles id key revoked revoked_at }

subject staffer { anchor tenant reach descendants identifies sub   roles configurable staff binds admin }
subject opser   { anchor tenant reach descendants identifies opsid roles configurable ops   binds owner }

object doc {
  table docs
  scoped tenant > project
  relation admin: staffer via role
  relation owner: opser   via owner_id
  permission view    = admin + owner @rls maps select
  permission publish = docs:publish @pdp
  permission run     = jobs:run @pdp
}
`
	s := mustValidSpec(t, spec)
	src, err := s.EmitFrameworkTS()
	if err != nil {
		t.Fatalf("EmitFrameworkTS: %v", err)
	}
	for _, want := range []string{
		"export const holdsResolverStaff: HoldsResolver =",
		"export const assignmentsSQLStaff =",
		"export function resolveHeldStaff(",
		"export async function holdsStaff(",
		"export const holdsResolverOps: HoldsResolver =",
		"export const assignmentsSQLOps =",
		"export function resolveHeldOps(",
		"export async function holdsOps(",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("multi-rolestore TS output missing %q", want)
		}
	}
	if strings.Contains(src, "export async function holds(q:") {
		t.Errorf("with >1 rolestore holds must be suffixed, not bare:\n%s", src)
	}
}

func TestEmitFrameworkTS_SQLMatchesGo(t *testing.T) {
	for _, name := range []string{"example.demesne", "roundtrip.demesne"} {
		src, err := os.ReadFile(filepath.Join("examples", name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		s, err := Parse(string(src))
		if err != nil {
			t.Fatalf("parse %s: %v", name, err)
		}
		if err := Validate(s); err != nil {
			t.Fatalf("validate %s: %v", name, err)
		}
		goOut, err := s.EmitFramework("authz")
		if err != nil {
			t.Fatalf("EmitFramework %s: %v", name, err)
		}
		tsOut, err := s.EmitFrameworkTS()
		if err != nil {
			t.Fatalf("EmitFrameworkTS %s: %v", name, err)
		}
		surf, err := s.EmitAppSurface()
		if err != nil {
			t.Fatalf("EmitAppSurface %s: %v", name, err)
		}

		var sqls []string
		for _, o := range surf.Objects {
			sqls = append(sqls, o.CheckSQL(), o.CheckManySQL(), o.ListResourcesSQL())
			if o.EditCheckSQL != "" {
				sqls = append(sqls, o.EditCheckSQL)
			}
			if o.FlatListFn != "" {
				sqls = append(sqls, o.ListResourcesFastSQL())
			}
		}
		if len(s.RoleStores) == 1 {
			hr, err := s.HoldsResolver("")
			if err != nil {
				t.Fatalf("HoldsResolver %s: %v", name, err)
			}
			sqls = append(sqls, hr.AssignmentsSQL())
		}

		for _, sql := range sqls {
			lit := fmt.Sprintf("%q", sql)
			if !strings.Contains(goOut, lit) {
				t.Errorf("%s: Go framework does not bake SQL %s", name, lit)
			}
			if !strings.Contains(tsOut, lit) {
				t.Errorf("%s: TS framework does not bake SQL %s", name, lit)
			}
		}
	}
}

func TestEmitFrameworkTS_Artifact(t *testing.T) {
	cases := []struct{ spec, out string }{
		{"roundtrip.demesne", filepath.Join("ts", "packages", "example-app", "generated", "framework.ts")},
		{"example.demesne", filepath.Join("ts", "packages", "example-app", "generated", "exampleFramework.ts")},
	}
	update := os.Getenv("UPDATE_ORACLE") != ""
	for _, c := range cases {
		src, err := os.ReadFile(filepath.Join("examples", c.spec))
		if err != nil {
			t.Fatalf("read %s: %v", c.spec, err)
		}
		s, err := Parse(string(src))
		if err != nil {
			t.Fatalf("parse %s: %v", c.spec, err)
		}
		if err := Validate(s); err != nil {
			t.Fatalf("validate %s: %v", c.spec, err)
		}
		gen, err := s.EmitFrameworkTS()
		if err != nil {
			t.Fatalf("EmitFrameworkTS %s: %v", c.spec, err)
		}
		if update {
			if err := os.MkdirAll(filepath.Dir(c.out), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(c.out, []byte(gen), 0o644); err != nil {
				t.Fatal(err)
			}
			t.Logf("wrote %s", c.out)
			continue
		}
		got, err := os.ReadFile(c.out)
		if err != nil {
			t.Fatalf("%s missing — run: UPDATE_ORACLE=1 go test -run TestEmitFrameworkTS_Artifact", c.out)
		}
		if string(got) != gen {
			t.Errorf("%s out of date — run: UPDATE_ORACLE=1 go test -run TestEmitFrameworkTS_Artifact", c.out)
		}
	}
}
