package demesne

import (
	"fmt"
	"go/format"
	"strings"
)

// Framework codegen (EID-289) — the leap from compiler to framework. The other emitters
// produce SQL (the moat) + plain-data projections (the runtime glue); this one produces the
// TYPED Go an app is built on: a `Claims` struct, the session envelope, per-object/per-verb
// `Can<Verb>` methods, scoped query builders, and a ready-to-mount HTTP check endpoint.
// "Define access in one file → get the code you need."
//
// The generated package IMPORTS the demesne engine for the shared runtime logic (Decision /
// ComposeCan / the holds-resolver) and bakes only the per-spec data + typed wrappers — the
// same split the TypeScript target (EID-338) makes (hand-written runtime + emitted
// projection). So the engine stays the single source of the composition rules; the
// generated code is a thin, typed, spec-shaped surface over it.
//
// `Can<Verb>` composes the right check per permission KIND: a read (`maps select`) runs the
// point-check; an edit (`maps update`) runs the edit point-check; a `@pdp` verb checks the
// subject's held permissions. Everything runs under the caller's minted claims + RLS role
// (the generated session envelope), so the database decides — equal by delegation.

// EmitFramework renders the spec as a self-describing typed Go package (DO NOT EDIT) in the
// given package name (default "authz"). It imports github.com/eidestudio/demesne.
func (s *Spec) EmitFramework(pkg string) (string, error) {
	if pkg == "" {
		pkg = "authz"
	}
	contract, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	surf, err := s.EmitAppSurface()
	if err != nil {
		return "", err
	}

	g := &fwGen{pkg: pkg, spec: s}
	g.header()
	g.preamble()
	g.claims(contract)
	for _, o := range surf.Objects {
		obj := s.objectByName(o.Object)
		if obj == nil {
			continue
		}
		if err := g.object(o, obj); err != nil {
			return "", err
		}
	}
	if len(s.RoleStores) > 0 {
		if err := g.holds(); err != nil {
			return "", err
		}
	}
	g.checkHandler(surf)

	// gofmt the output — guarantees canonical formatting AND parses it (a syntax error in
	// the generator surfaces here, not at the adopter's compile).
	formatted, err := format.Source([]byte(g.b.String()))
	if err != nil {
		return "", fmt.Errorf("EmitFramework: generated code does not parse: %w", err)
	}
	return string(formatted), nil
}

type fwGen struct {
	pkg  string
	spec *Spec
	b    strings.Builder
	// checks accumulates (object, method, kind) for the HTTP dispatcher; kind is
	// "row" (Can takes ctx,q,id) — only row checks are dispatchable by id.
	checks []fwCheck
}

type fwCheck struct{ object, verb, method string }

func (g *fwGen) header() {
	fmt.Fprintf(&g.b, "// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	fmt.Fprintf(&g.b, "//\n// The typed app surface: Claims + session, per-object Can<Verb>, scoped query\n")
	fmt.Fprintf(&g.b, "// builders, and an HTTP check endpoint. Imports the demesne engine for the shared\n")
	fmt.Fprintf(&g.b, "// composition rules; everything runs under the caller's claims so the DB decides.\n\n")
	fmt.Fprintf(&g.b, "package %s\n\n", g.pkg)
	g.b.WriteString("import (\n")
	g.b.WriteString("\t\"context\"\n")
	g.b.WriteString("\t\"database/sql\"\n")
	g.b.WriteString("\t\"encoding/json\"\n")
	g.b.WriteString("\t\"net/http\"\n\n")
	g.b.WriteString("\tdemesne \"github.com/eidestudio/demesne\"\n")
	g.b.WriteString(")\n\n")
}

func (g *fwGen) preamble() {
	g.b.WriteString(`// Decision is the engine's authorization decision tri-state, re-exported so callers
// need not import the engine directly.
type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

// Row / Rows / Querier are the minimal DB surface the checks need. database/sql (via
// FromSQL), pgx, and any wrapper satisfy them.
type Row interface {
	Scan(dest ...any) error
}

type Rows interface {
	Next() bool
	Scan(dest ...any) error
	Close() error
	Err() error
}

type Querier interface {
	QueryRowContext(ctx context.Context, query string, args ...any) Row
	QueryContext(ctx context.Context, query string, args ...any) (Rows, error)
}

// sqlDB is the subset of *sql.DB / *sql.Tx that FromSQL adapts to Querier.
type sqlDB interface {
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

type sqlQuerier struct{ db sqlDB }

func (q sqlQuerier) QueryRowContext(ctx context.Context, query string, args ...any) Row {
	return q.db.QueryRowContext(ctx, query, args...)
}

func (q sqlQuerier) QueryContext(ctx context.Context, query string, args ...any) (Rows, error) {
	return q.db.QueryContext(ctx, query, args...)
}

// FromSQL adapts a database/sql *DB or *Tx to Querier.
func FromSQL(db sqlDB) Querier { return sqlQuerier{db} }

`)
}

func (g *fwGen) claims(contract []string) {
	setting, _ := g.spec.claimSetting()
	role := g.spec.claimRole()

	g.b.WriteString("// claimsContract is the spec's claim key set (byte-sorted) — the keys Claims mints.\n")
	fmt.Fprintf(&g.b, "var claimsContract = %s\n\n", goStrSlice(contract))

	g.b.WriteString("// Claims is the typed claims contract — one field per key. A zero-value field is\n")
	g.b.WriteString("// omitted from the minted blob (a principal supplies only the keys it has).\n")
	g.b.WriteString("type Claims struct {\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "\t%s string\n", goExport(k))
	}
	g.b.WriteString("}\n\n")

	g.b.WriteString("func (c Claims) values() map[string]string {\n")
	g.b.WriteString("\tm := map[string]string{}\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "\tif c.%s != \"\" {\n\t\tm[%q] = c.%s\n\t}\n", goExport(k), k, goExport(k))
	}
	g.b.WriteString("\treturn m\n}\n\n")

	g.b.WriteString("// Mint renders the deterministic claims blob (sorted keys) to install in the GUC.\n")
	g.b.WriteString("func (c Claims) Mint() (string, error) {\n")
	g.b.WriteString("\treturn demesne.MintClaimsValues(claimsContract, c.values())\n}\n\n")

	fmt.Fprintf(&g.b, "// The RLS connection role + claims GUC the session assumes (spec-declared, defaulted).\n")
	fmt.Fprintf(&g.b, "const ConnectionRole = %q\n", role)
	fmt.Fprintf(&g.b, "const claimsGUC = %q\n\n", setting)

	g.b.WriteString(`// SetRoleSQL assumes the RLS connection role so policies evaluate; local scopes it to
// the current transaction.
func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

// ClaimsSetSQL installs the minted claims blob ($1) into the GUC the policies read.
func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

// SessionSetupSQL is the WithRLS envelope: assume the role, then install the claims. Run in
// order at the top of an RLS transaction; the SECOND statement binds the Mint() result to $1.
func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

`)
}

// object emits one object's typed access surface: its Can<Verb> methods (read / edit), the
// scoped query builders, and any @pdp verb checks.
func (g *fwGen) object(o AppObjectSurface, obj *Object) error {
	recv := unexport(o.Object) + "Access"
	exp := goExport(o.Object)

	fmt.Fprintf(&g.b, "// %s is the typed access surface for the %q object (table %s, pk %s).\n", exp, o.Object, o.Table, o.PK)
	fmt.Fprintf(&g.b, "type %s struct{}\n\n", recv)
	fmt.Fprintf(&g.b, "var %s = %s{}\n\n", exp, recv)

	for _, pm := range obj.Perms {
		verb := goExport(pm.Verb)
		switch {
		case containsStr(pm.Layers, "pdp"):
			g.pdpCan(recv, exp, pm)
		case pm.Maps == "select":
			g.rowCan(recv, exp, o.Object, pm.Verb, "Can"+verb, o.CheckSQL(),
				fmt.Sprintf("can SEE the %s row (its read policy)", o.Object))
		case pm.Maps == "update":
			if o.EditCheckSQL == "" {
				continue
			}
			g.rowCan(recv, exp, o.Object, pm.Verb, "Can"+verb, o.EditCheckSQL,
				fmt.Sprintf("can EDIT the %s row (visible AND its update policy)", o.Object))
		default:
			// insert/delete and unmapped verbs have no row point-check; skipped.
		}
	}

	// Scoped query builders: keyset list + batch check, run under the caller's session.
	fmt.Fprintf(&g.b, "// ListResources returns a keyset page of the %s rows the caller can SEE (PK order).\n", o.Object)
	fmt.Fprintf(&g.b, "// after is the last PK of the previous page (nil for the first); limit is the page size.\n")
	fmt.Fprintf(&g.b, "func (%s) ListResources(ctx context.Context, q Querier, after *string, limit int) ([]string, error) {\n", recv)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, after, limit)\n", goRawString(o.ListResourcesSQL()))
	g.b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar out []string\n\tfor rows.Next() {\n\t\tvar id string\n\t\tif err := rows.Scan(&id); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tout = append(out, id)\n\t}\n\treturn out, rows.Err()\n}\n\n")

	fmt.Fprintf(&g.b, "// CheckMany returns the subset of ids the caller can SEE (one round-trip).\n")
	fmt.Fprintf(&g.b, "func (%s) CheckMany(ctx context.Context, q Querier, ids []string) ([]string, error) {\n", recv)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, ids)\n", goRawString(o.CheckManySQL()))
	g.b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar out []string\n\tfor rows.Next() {\n\t\tvar id string\n\t\tif err := rows.Scan(&id); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tout = append(out, id)\n\t}\n\treturn out, rows.Err()\n}\n\n")
	return nil
}

// rowCan emits a point-check Can method (read or edit) and registers it for the HTTP endpoint.
func (g *fwGen) rowCan(recv, exp, object, verb, method, sql, doc string) {
	fmt.Fprintf(&g.b, "// %s reports whether the caller %s. Run under the caller's claims + RLS role.\n", method, doc)
	fmt.Fprintf(&g.b, "func (%s) %s(ctx context.Context, q Querier, id string) (Decision, error) {\n", recv, method)
	g.b.WriteString("\tvar ok bool\n")
	fmt.Fprintf(&g.b, "\tif err := q.QueryRowContext(ctx, %s, id).Scan(&ok); err != nil {\n", goRawString(sql))
	g.b.WriteString("\t\treturn Deny, err\n\t}\n")
	g.b.WriteString("\treturn demesne.ComposeCan(true, ok, demesne.NotGoverned), nil\n}\n\n")
	g.checks = append(g.checks, fwCheck{object: object, verb: verb, method: exp + "." + method})
}

// pdpCan emits a @pdp verb check: the caller's held permissions decide (no row predicate).
func (g *fwGen) pdpCan(recv, exp string, pm *Perm) {
	var perms []string
	for _, t := range pm.Expr {
		if t.Ident != "" {
			perms = append(perms, t.Ident)
		}
	}
	method := "Can" + goExport(pm.Verb)
	fmt.Fprintf(&g.b, "// %s reports whether the caller's held permissions admit %q (a @pdp verb — no row\n", method, pm.Verb)
	fmt.Fprintf(&g.b, "// predicate). Resolve `held` with Holds(...).\n")
	fmt.Fprintf(&g.b, "func (%s) %s(held demesne.EffectivePerms) Decision {\n", recv, method)
	for _, p := range perms {
		fmt.Fprintf(&g.b, "\tif !held.Holds(%q) {\n\t\treturn Deny\n\t}\n", p)
	}
	g.b.WriteString("\treturn Allow\n}\n\n")
}

// holds emits the holds-resolver: the baked projection + a Holds(...) helper that reads a
// principal's active assignments and resolves the effective permission set at a scope.
func (g *fwGen) holds() error {
	r, err := g.spec.HoldsResolver("")
	if err != nil {
		return err
	}
	g.b.WriteString("// holdsResolver is the rolestore projection the engine resolves held permissions over.\n")
	fmt.Fprintf(&g.b, "var holdsResolver = %s\n\n", g.resolverLit(r))

	matComment := ""
	if r.PermsCol != "" {
		matComment = " (the materialized permissions column is scanned as []string — use a driver\n" +
			"// that scans text[] into []string, e.g. pgx; database/sql users wrap with pq.Array)"
	}
	fmt.Fprintf(&g.b, "// Holds resolves a principal's effective permissions at a scope%s.\n", matComment)
	g.b.WriteString("// scope is the scope-column values root->leaf; an empty string leaves a level unpinned.\n")
	g.b.WriteString("func Holds(ctx context.Context, q Querier, principalID string, scope []string) (demesne.EffectivePerms, error) {\n")
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, principalID)\n", goRawString(r.AssignmentsSQL()))
	g.b.WriteString("\tif err != nil {\n\t\treturn demesne.EffectivePerms{}, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar assignments []demesne.RoleAssignment\n")
	g.b.WriteString("\tfor rows.Next() {\n")
	fmt.Fprintf(&g.b, "\t\ta := demesne.RoleAssignment{Scope: make([]string, %d)}\n", len(r.ScopeCols))
	dest := make([]string, 0, len(r.ScopeCols)+2)
	for i := range r.ScopeCols {
		dest = append(dest, fmt.Sprintf("&a.Scope[%d]", i))
	}
	dest = append(dest, "&a.RoleKey")
	if r.PermsCol != "" {
		dest = append(dest, "&a.Permissions")
	}
	fmt.Fprintf(&g.b, "\t\tif err := rows.Scan(%s); err != nil {\n", strings.Join(dest, ", "))
	g.b.WriteString("\t\t\treturn demesne.EffectivePerms{}, err\n\t\t}\n")
	g.b.WriteString("\t\tassignments = append(assignments, a)\n\t}\n")
	g.b.WriteString("\tif err := rows.Err(); err != nil {\n\t\treturn demesne.EffectivePerms{}, err\n\t}\n")
	g.b.WriteString("\treturn holdsResolver.Resolve(assignments, scope)\n}\n\n")
	return nil
}

// checkHandler emits a ready-to-mount HTTP endpoint over the row Can<Verb> checks:
// GET/POST ?object=&verb=&id= → {"decision":"allow|deny|ungoverned"}. The caller wraps it
// with the request's session (claims already set on q).
func (g *fwGen) checkHandler(surf *AppCheckSurface) {
	g.b.WriteString("// CheckHandler answers the app-level read/edit check over the row Can<Verb> methods:\n")
	g.b.WriteString("//   ?object=<o>&verb=<v>&id=<id>  ->  {\"decision\":\"allow|deny|ungoverned\"}\n")
	g.b.WriteString("// Pass a Querier already bound to the request's session (role + claims set).\n")
	g.b.WriteString("func CheckHandler(q Querier) http.HandlerFunc {\n")
	g.b.WriteString("\treturn func(w http.ResponseWriter, r *http.Request) {\n")
	g.b.WriteString("\t\tobject, verb, id := r.FormValue(\"object\"), r.FormValue(\"verb\"), r.FormValue(\"id\")\n")
	g.b.WriteString("\t\tvar (\n\t\t\td   Decision\n\t\t\terr error\n\t\t)\n")
	g.b.WriteString("\t\tswitch object + \".\" + verb {\n")
	for _, c := range g.checks {
		fmt.Fprintf(&g.b, "\t\tcase %q:\n\t\t\td, err = %s(r.Context(), q, id)\n", c.object+"."+c.verb, c.method)
	}
	g.b.WriteString("\t\tdefault:\n\t\t\thttp.Error(w, \"unknown object/verb\", http.StatusNotFound)\n\t\t\treturn\n\t\t}\n")
	g.b.WriteString("\t\tif err != nil {\n\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n\t\t\treturn\n\t\t}\n")
	g.b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	g.b.WriteString("\t\t_ = json.NewEncoder(w).Encode(map[string]string{\"decision\": d.String()})\n")
	g.b.WriteString("\t}\n}\n")
}

// --- Go-literal helpers -----------------------------------------------------------

// resolverLit renders a *HoldsResolver as a Go composite literal (incl. its Vocab).
func (g *fwGen) resolverLit(r *HoldsResolver) string {
	var b strings.Builder
	b.WriteString("&demesne.HoldsResolver{\n")
	fmt.Fprintf(&b, "\tAssignments: %q,\n", r.Assignments)
	fmt.Fprintf(&b, "\tKindCol:     %q,\n", r.KindCol)
	fmt.Fprintf(&b, "\tKindVal:     %q,\n", r.KindVal)
	fmt.Fprintf(&b, "\tSubjectCol:  %q,\n", r.SubjectCol)
	fmt.Fprintf(&b, "\tScopeCols:   %s,\n", goStrSlice(r.ScopeCols))
	fmt.Fprintf(&b, "\tRevokedCol:  %q,\n", r.RevokedCol)
	fmt.Fprintf(&b, "\tRoleCol:     %q,\n", r.RoleCol)
	fmt.Fprintf(&b, "\tRolesTable:  %q,\n", r.RolesTable)
	fmt.Fprintf(&b, "\tRolesID:     %q,\n", r.RolesID)
	fmt.Fprintf(&b, "\tKeyCol:      %q,\n", r.KeyCol)
	fmt.Fprintf(&b, "\tPermsCol:    %q,\n", r.PermsCol)
	fmt.Fprintf(&b, "\tVocab:       %s,\n", g.vocabLit(r.Vocab))
	b.WriteString("}")
	return b.String()
}

func (g *fwGen) vocabLit(v *Vocabulary) string {
	if v == nil {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("&demesne.Vocabulary{\n")
	fmt.Fprintf(&b, "\t\tName:        %q,\n", v.Name)
	fmt.Fprintf(&b, "\t\tPermissions: %s,\n", goStrSlice(v.Permissions))
	if len(v.Presets) > 0 {
		b.WriteString("\t\tPresets: []*demesne.Preset{\n")
		for _, p := range v.Presets {
			fmt.Fprintf(&b, "\t\t\t{Name: %q, Level: %q, Star: %t, Set: %s},\n", p.Name, p.Level, p.Star, goStrSlice(p.Set))
		}
		b.WriteString("\t\t},\n")
	}
	fmt.Fprintf(&b, "\t\tRank:        %s,\n", goStrSlice(v.Rank))
	b.WriteString("\t}")
	return b.String()
}

// goStrSlice renders a []string as a Go composite literal (nil/empty → []string{}).
func goStrSlice(ss []string) string {
	if len(ss) == 0 {
		return "[]string{}"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// goRawString renders s as a Go double-quoted string literal (SQL has no backticks/newlines).
func goRawString(s string) string { return fmt.Sprintf("%q", s) }

// goExport converts a snake/kebab/colon identifier to an exported Go name (id -> ID).
func goExport(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ':' || r == '.' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		if up := strings.ToUpper(p); commonInitialisms[up] {
			parts[i] = up
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// unexport lowercases the first rune (for a private receiver type name).
func unexport(s string) string {
	e := goExport(s)
	if e == "" {
		return e
	}
	return strings.ToLower(e[:1]) + e[1:]
}

var commonInitialisms = map[string]bool{"ID": true, "URL": true, "API": true, "SQL": true, "UID": true, "ACL": true, "PK": true}

func containsStr(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}
