package demesne

import (
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

func (s *Spec) EmitFramework(pkg string) (string, error) {
	if pkg == "" {
		pkg = "authz"
	}
	contract, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	surf, err := s.EmitAppSurface()
	if err != nil {
		return "", err
	}

	skipped := s.compositePKObjects()
	orphanPDP := s.orphanPDPVerbs()

	g := &fwGen{pkg: pkg, spec: s}
	g.header()
	g.preamble()
	g.claims(contract)
	g.banner(skipped)
	g.pdpBanner(orphanPDP)
	for _, o := range surf.Objects {
		obj := s.objectByName(o.Object)
		if obj == nil {
			continue
		}
		g.object(o, obj)
	}
	for _, rs := range s.RoleStores {
		suffix := ""
		if len(s.RoleStores) > 1 {
			suffix = goExport(rs.Name)
		}
		if err := g.holds(rs, suffix); err != nil {
			return "", err
		}
	}
	g.checkFunc()
	g.checkHandler()

	formatted, err := format.Source([]byte(g.b.String()))
	if err != nil {
		return "", fmt.Errorf("EmitFramework: generated code does not parse: %w", err)
	}
	return string(formatted), nil
}

func (s *Spec) compositePKObjects() []*Object {
	var skipped []*Object
	for _, o := range s.Objects {
		if !o.pointCheckable() {
			skipped = append(skipped, o)
		}
	}
	return skipped
}

func (s *Spec) orphanPDPVerbs() []string {
	covered := map[string]bool{}
	for _, rs := range s.RoleStores {
		if v, err := s.rolestoreVocab(rs); err == nil && v != nil {
			for _, p := range v.Permissions {
				covered[p] = true
			}
		}
	}
	var orphan []string
	for _, o := range s.Objects {
		if !o.pointCheckable() {
			continue
		}
		for _, pm := range o.Perms {
			if !containsStr(pm.Layers, "pdp") {
				continue
			}
			for _, tok := range pm.Expr {
				if tok.Ident != "" && !covered[tok.Ident] {
					orphan = append(orphan, fmt.Sprintf("%s.%s (needs %q)", o.Name, pm.Verb, tok.Ident))
				}
			}
		}
	}
	return orphan
}

type fwGen struct {
	pkg    string
	spec   *Spec
	b      strings.Builder
	checks []fwCheck
}

type fwCheck struct{ object, verb, method string }

func (g *fwGen) header() {
	g.b.WriteString("// Code generated by Demesne. DO NOT EDIT.\n\n")
	fmt.Fprintf(&g.b, "package %s\n\n", g.pkg)
	g.b.WriteString("import (\n")
	g.b.WriteString("\t\"context\"\n")
	g.b.WriteString("\t\"encoding/json\"\n")
	g.b.WriteString("\t\"net/http\"\n\n")
	g.b.WriteString("\tdemesne \"github.com/eidestudio/demesne\"\n")
	g.b.WriteString(")\n\n")
}

func (g *fwGen) preamble() {
	g.b.WriteString(`type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

`)
}

func (g *fwGen) claims(contract []string) {
	setting, _ := g.spec.claimSetting()
	role := g.spec.claimRole()

	fmt.Fprintf(&g.b, "var claimsContract = %s\n\n", goStrSlice(contract))

	g.b.WriteString("type Claims struct {\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "\t%s string\n", goExport(k))
	}
	g.b.WriteString("\tExtra map[string]string\n")
	g.b.WriteString("}\n\n")

	g.b.WriteString("func (c Claims) values() map[string]string {\n")
	g.b.WriteString("\tm := map[string]string{}\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "\tif c.%s != \"\" {\n\t\tm[%q] = c.%s\n\t}\n", goExport(k), k, goExport(k))
	}
	g.b.WriteString("\treturn m\n}\n\n")

	g.b.WriteString("func (c Claims) Mint() (string, error) {\n")
	g.b.WriteString("\treturn demesne.MintClaimsValuesWithExtra(claimsContract, c.values(), c.Extra)\n}\n\n")

	fmt.Fprintf(&g.b, "const ConnectionRole = %q\n", role)
	fmt.Fprintf(&g.b, "const claimsGUC = %q\n\n", setting)

	g.b.WriteString(`func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

`)
}

func (g *fwGen) banner(skipped []*Object) {
	if len(skipped) == 0 {
		return
	}
	g.b.WriteString("// These objects declare a composite primary key — no single-column row identity, so no\n")
	g.b.WriteString("// Can / ListResources / CheckMany is generated for them. Reach such rows via your own\n")
	g.b.WriteString("// predicate or a related object:\n")
	for _, o := range skipped {
		fmt.Fprintf(&g.b, "//   - %s (table %s, pk %s)\n", o.Name, o.Table, strings.Join(o.PKCols, ", "))
	}
	g.b.WriteString("\n")
}

func (g *fwGen) pdpBanner(orphan []string) {
	if len(orphan) == 0 {
		return
	}
	g.b.WriteString("// These @pdp verbs need a permission no rolestore vocabulary covers, so no Holds\n")
	g.b.WriteString("// resolver is generated for them — resolve their held input yourself, or add a rolestore\n")
	g.b.WriteString("// for the permission's vocabulary:\n")
	for _, v := range orphan {
		fmt.Fprintf(&g.b, "//   - %s\n", v)
	}
	g.b.WriteString("\n")
}

func (g *fwGen) object(o AppObjectSurface, obj *Object) {
	recv := unexport(o.Object) + "Access"
	exp := goExport(o.Object)

	fmt.Fprintf(&g.b, "type %s struct{}\n\n", recv)
	fmt.Fprintf(&g.b, "var %s = %s{}\n\n", exp, recv)

	for _, pm := range obj.Perms {
		verb := goExport(pm.Verb)
		switch {
		case containsStr(pm.Layers, "pdp"):
			g.pdpCan(recv, pm)
		case pm.Maps == "select":
			g.rowCan(recv, exp, o.Object, pm.Verb, "Can"+verb, o.CheckSQL())
		case pm.Maps == "update":
			if o.EditCheckSQL == "" {
				continue
			}
			g.rowCan(recv, exp, o.Object, pm.Verb, "Can"+verb, o.EditCheckSQL)
		}
	}

	listSQL := o.ListResourcesSQL()
	if o.FlatListFn != "" {
		listSQL = o.ListResourcesFastSQL()
	}
	fmt.Fprintf(&g.b, "func (%s) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {\n", recv)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, after, limit)\n", goRawString(listSQL))
	g.scanIDs()

	fmt.Fprintf(&g.b, "func (%s) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {\n", recv)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, %s, ids)\n", goRawString(o.CheckManySQL()))
	g.scanIDs()
}

func (g *fwGen) scanIDs() {
	g.b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar out []string\n\tfor rows.Next() {\n\t\tvar id string\n\t\tif err := rows.Scan(&id); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tout = append(out, id)\n\t}\n\treturn out, rows.Err()\n}\n\n")
}

func (g *fwGen) rowCan(recv, exp, object, verb, method, sql string) {
	fmt.Fprintf(&g.b, "func (%s) %s(ctx context.Context, q demesne.Querier, id string) (Decision, error) {\n", recv, method)
	g.b.WriteString("\tvar ok bool\n")
	fmt.Fprintf(&g.b, "\tif err := q.QueryRowContext(ctx, %s, id).Scan(&ok); err != nil {\n", goRawString(sql))
	g.b.WriteString("\t\treturn Deny, err\n\t}\n")
	g.b.WriteString("\treturn demesne.ComposeCan(true, ok, demesne.NotGoverned), nil\n}\n\n")
	g.checks = append(g.checks, fwCheck{object: object, verb: verb, method: exp + "." + method})
}

func (g *fwGen) pdpCan(recv string, pm *Perm) {
	var perms []string
	for _, t := range pm.Expr {
		if t.Ident != "" {
			perms = append(perms, t.Ident)
		}
	}
	method := "Can" + goExport(pm.Verb)
	fmt.Fprintf(&g.b, "func (%s) %s(held demesne.EffectivePerms) Decision {\n", recv, method)
	for _, p := range perms {
		fmt.Fprintf(&g.b, "\tif !held.Holds(%q) {\n\t\treturn Deny\n\t}\n", p)
	}
	g.b.WriteString("\treturn Allow\n}\n\n")
}

func (g *fwGen) holds(rs *RoleStore, suffix string) error {
	r, err := g.spec.HoldsResolver(rs.Name)
	if err != nil {
		return err
	}
	fmt.Fprintf(&g.b, "var holdsResolver%s = %s\n\n", suffix, g.resolverLit(r))
	fmt.Fprintf(&g.b, "const AssignmentsSQL%s = %s\n\n", suffix, goRawString(r.AssignmentsSQL()))

	fmt.Fprintf(&g.b, "func ResolveHeld%s(assignments []demesne.RoleAssignment, scope []string) (demesne.EffectivePerms, error) {\n", suffix)
	fmt.Fprintf(&g.b, "\treturn holdsResolver%s.Resolve(assignments, scope)\n}\n\n", suffix)

	fmt.Fprintf(&g.b, "func Holds%s(ctx context.Context, q demesne.Querier, principalID string, scope []string) (demesne.EffectivePerms, error) {\n", suffix)
	fmt.Fprintf(&g.b, "\trows, err := q.QueryContext(ctx, AssignmentsSQL%s, principalID)\n", suffix)
	g.b.WriteString("\tif err != nil {\n\t\treturn demesne.EffectivePerms{}, err\n\t}\n\tdefer rows.Close()\n")
	g.b.WriteString("\tvar assignments []demesne.RoleAssignment\n")
	g.b.WriteString("\tfor rows.Next() {\n")
	fmt.Fprintf(&g.b, "\t\ta := demesne.RoleAssignment{Scope: make([]string, %d)}\n", len(r.ScopeCols))
	dest := make([]string, 0, len(r.ScopeCols)+2)
	for i := range r.ScopeCols {
		dest = append(dest, fmt.Sprintf("&a.Scope[%d]", i))
	}
	dest = append(dest, "&a.RoleKey")
	if r.PermsCol != "" {
		dest = append(dest, "&a.Permissions")
	}
	fmt.Fprintf(&g.b, "\t\tif err := rows.Scan(%s); err != nil {\n", strings.Join(dest, ", "))
	g.b.WriteString("\t\t\treturn demesne.EffectivePerms{}, err\n\t\t}\n")
	g.b.WriteString("\t\tassignments = append(assignments, a)\n\t}\n")
	g.b.WriteString("\tif err := rows.Err(); err != nil {\n\t\treturn demesne.EffectivePerms{}, err\n\t}\n")
	fmt.Fprintf(&g.b, "\treturn ResolveHeld%s(assignments, scope)\n}\n\n", suffix)
	return nil
}

func (g *fwGen) checkFunc() {
	g.b.WriteString("func Check(ctx context.Context, q demesne.Querier, object, verb, id string) (Decision, error) {\n")
	g.b.WriteString("\tswitch object + \".\" + verb {\n")
	for _, c := range g.checks {
		fmt.Fprintf(&g.b, "\tcase %q:\n\t\treturn %s(ctx, q, id)\n", c.object+"."+c.verb, c.method)
	}
	g.b.WriteString("\tdefault:\n\t\treturn NotGoverned, nil\n\t}\n}\n\n")
}

func (g *fwGen) checkHandler() {
	g.b.WriteString("func CheckHandler(q demesne.Querier) http.HandlerFunc {\n")
	g.b.WriteString("\treturn func(w http.ResponseWriter, r *http.Request) {\n")
	g.b.WriteString("\t\td, err := Check(r.Context(), q, r.FormValue(\"object\"), r.FormValue(\"verb\"), r.FormValue(\"id\"))\n")
	g.b.WriteString("\t\tif err != nil {\n\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n\t\t\treturn\n\t\t}\n")
	g.b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	g.b.WriteString("\t\t_ = json.NewEncoder(w).Encode(map[string]string{\"decision\": d.String()})\n")
	g.b.WriteString("\t}\n}\n")
}

func (g *fwGen) resolverLit(r *HoldsResolver) string {
	var b strings.Builder
	b.WriteString("&demesne.HoldsResolver{\n")
	fmt.Fprintf(&b, "\tAssignments: %q,\n", r.Assignments)
	fmt.Fprintf(&b, "\tKindCol:     %q,\n", r.KindCol)
	fmt.Fprintf(&b, "\tKindVal:     %q,\n", r.KindVal)
	fmt.Fprintf(&b, "\tSubjectCol:  %q,\n", r.SubjectCol)
	fmt.Fprintf(&b, "\tScopeCols:   %s,\n", goStrSlice(r.ScopeCols))
	fmt.Fprintf(&b, "\tRevokedCol:  %q,\n", r.RevokedCol)
	fmt.Fprintf(&b, "\tRoleCol:     %q,\n", r.RoleCol)
	fmt.Fprintf(&b, "\tRolesTable:  %q,\n", r.RolesTable)
	fmt.Fprintf(&b, "\tRolesID:     %q,\n", r.RolesID)
	fmt.Fprintf(&b, "\tKeyCol:      %q,\n", r.KeyCol)
	fmt.Fprintf(&b, "\tPermsCol:    %q,\n", r.PermsCol)
	fmt.Fprintf(&b, "\tVocab:       %s,\n", g.vocabLit(r.Vocab))
	b.WriteString("}")
	return b.String()
}

func (g *fwGen) vocabLit(v *Vocabulary) string {
	if v == nil {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("&demesne.Vocabulary{\n")
	fmt.Fprintf(&b, "\t\tName:        %q,\n", v.Name)
	fmt.Fprintf(&b, "\t\tPermissions: %s,\n", goStrSlice(v.Permissions))
	if len(v.Presets) > 0 {
		b.WriteString("\t\tPresets: []*demesne.Preset{\n")
		for _, p := range v.Presets {
			fmt.Fprintf(&b, "\t\t\t{Name: %q, Level: %q, Star: %t, Set: %s},\n", p.Name, p.Level, p.Star, goStrSlice(p.Set))
		}
		b.WriteString("\t\t},\n")
	}
	fmt.Fprintf(&b, "\t\tRank:        %s,\n", goStrSlice(v.Rank))
	b.WriteString("\t}")
	return b.String()
}

func goStrSlice(ss []string) string {
	if len(ss) == 0 {
		return "[]string{}"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func goRawString(s string) string { return fmt.Sprintf("%q", s) }

func goExport(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ':' || r == '.' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		if up := strings.ToUpper(p); commonInitialisms[up] {
			parts[i] = up
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func unexport(s string) string {
	r := []rune(goExport(s))
	if len(r) == 0 {
		return ""
	}
	i := 0
	for i < len(r) && unicode.IsUpper(r[i]) {
		i++
	}
	if i == len(r) {
		return strings.ToLower(string(r))
	}
	if i > 1 {
		i--
	}
	return strings.ToLower(string(r[:i])) + string(r[i:])
}

var commonInitialisms = map[string]bool{"ID": true, "URL": true, "API": true, "SQL": true, "UID": true, "ACL": true, "PK": true}

func containsStr(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}
