package demesne

import (
	"fmt"
	"strings"
)

const supabaseHookFn = "demesne_access_token_hook"

const supabaseGUC = "request.jwt.claims"

func (s *Spec) EmitSupabaseProfile() (string, error) {
	setting, cast := s.claimSetting()
	if setting != supabaseGUC {
		return "", fmt.Errorf(
			"EmitSupabaseProfile: spec claims setting is %q, but Supabase's PostgREST populates only %q — remove the custom `claims via` setting for the Supabase profile",
			setting, supabaseGUC)
	}
	keys, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	role := s.claimRole()

	var b strings.Builder
	b.WriteString("-- Code generated by Demesne — Supabase deployment profile. DO NOT EDIT.\n")
	b.WriteString("--\n")
	b.WriteString("-- Register this function as the \"Custom Access Token\" auth hook (Dashboard -> Auth ->\n")
	b.WriteString("-- Hooks, or config.toml [auth.hook.custom_access_token]). It lifts each Demesne\n")
	b.WriteString("-- claims-contract key from a user's app_metadata into the JWT, so the generated RLS\n")
	fmt.Fprintf(&b, "-- policies -- which read current_setting('%s', true)::%s ->> '<key>' -- see them.\n", setting, cast)
	b.WriteString("-- Populate app_metadata with these keys via BuildClaims + the Supabase admin API.\n")
	b.WriteString("--\n")
	fmt.Fprintf(&b, "-- The RLS connection role is %q (non-BYPASSRLS -- the moat). service_role (BYPASSRLS)\n", role)
	b.WriteString("-- must be used ONLY for trusted server-side / bootstrap paths, NEVER the request path:\n")
	b.WriteString("-- a request-path query under service_role silently bypasses every policy.\n\n")

	fmt.Fprintf(&b, "create or replace function public.%s(event jsonb)\n", supabaseHookFn)
	b.WriteString("returns jsonb\n")
	b.WriteString("language plpgsql\n")
	b.WriteString("stable\n")
	b.WriteString("as $$\n")
	b.WriteString("declare\n")
	b.WriteString("  claims jsonb;\n")
	b.WriteString("  meta jsonb;\n")
	b.WriteString("begin\n")
	b.WriteString("  claims := event->'claims';\n")
	b.WriteString("  meta := coalesce(claims->'app_metadata', '{}'::jsonb);\n")
	b.WriteString("  -- one lift per Demesne claims-contract key (app_metadata -> top-level claim):\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "  if meta ? '%s' then claims := jsonb_set(claims, '{%s}', meta->'%s'); end if;\n", k, k, k)
	}
	b.WriteString("  event := jsonb_set(event, '{claims}', claims);\n")
	b.WriteString("  return event;\n")
	b.WriteString("end;\n")
	b.WriteString("$$;\n\n")

	fmt.Fprintf(&b, "grant execute on function public.%s to supabase_auth_admin;\n", supabaseHookFn)
	b.WriteString("grant usage on schema public to supabase_auth_admin;\n")
	fmt.Fprintf(&b, "revoke execute on function public.%s from authenticated, anon, public;\n", supabaseHookFn)

	return b.String(), nil
}
