package demesne

import (
	"fmt"
	"sort"
	"strings"
)

type FieldAccess struct {
	Object     string
	Principals []string
	Rules      []FieldAccessRule
}

type FieldAccessRule struct {
	Field  string
	Read   []string
	Write  []string
	Column string
}

func (s *Spec) EmitFieldAccess() (map[string]*FieldAccess, error) {
	out := map[string]*FieldAccess{}
	for _, o := range s.Objects {
		if len(o.FieldPrincipals) == 0 {
			continue
		}
		principals := append([]string(nil), o.FieldPrincipals...)
		sort.Strings(principals)
		fa := &FieldAccess{Object: o.Name, Principals: principals}
		for _, f := range o.Fields {
			fa.Rules = append(fa.Rules, FieldAccessRule{
				Field:  f.Name,
				Read:   append([]string(nil), f.Read...),
				Write:  append([]string(nil), f.Write...),
				Column: f.Column,
			})
		}
		out[o.Name] = fa
	}
	return out, nil
}

func (fa *FieldAccess) typeName() string { return goExport(fa.Object) }

func (fa *FieldAccess) principalType() string { return fa.typeName() + "FieldPrincipal" }

func (fa *FieldAccess) constName(token string) string {
	return fa.typeName() + "Field" + goExport(token)
}

func (fa *FieldAccess) RenderGo() string {
	tn := fa.typeName()
	pt := fa.principalType()
	policy := tn + "FieldPolicy"
	helper := unexport(fa.Object) + "FieldAllowed"

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by Demesne field-access (object %q). DO NOT EDIT.\n\n", fa.Object)

	fmt.Fprintf(&b, "type %s string\n\n", pt)
	b.WriteString("const (\n")
	for _, tok := range fa.Principals {
		fmt.Fprintf(&b, "\t%s %s = %q\n", fa.constName(tok), pt, tok)
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "type %s struct {\n\tread  map[string][]%s\n\twrite map[string][]%s\n}\n\n", policy, pt, pt)

	fmt.Fprintf(&b, "func New%s() *%s {\n", policy, policy)
	fmt.Fprintf(&b, "\tp := &%s{read: map[string][]%s{}, write: map[string][]%s{}}\n", policy, pt, pt)
	for _, r := range fa.Rules {
		if len(r.Read) > 0 {
			fmt.Fprintf(&b, "\tp.read[%q] = %s\n", r.Field, fa.sliceLit(r.Read))
		}
		if len(r.Write) > 0 {
			fmt.Fprintf(&b, "\tp.write[%q] = %s\n", r.Field, fa.sliceLit(r.Write))
		}
	}
	b.WriteString("\treturn p\n}\n\n")

	fmt.Fprintf(&b, "func (p *%s) SetRead(field string, who ...%s)  { p.read[field] = who }\n", policy, pt)
	fmt.Fprintf(&b, "func (p *%s) SetWrite(field string, who ...%s) { p.write[field] = who }\n\n", policy, pt)

	fmt.Fprintf(&b, "func (p *%s) CanReadField(field string, who %s) bool  { return %s(p.read, field, who) }\n", policy, pt, helper)
	fmt.Fprintf(&b, "func (p *%s) CanWriteField(field string, who %s) bool { return %s(p.write, field, who) }\n\n", policy, pt, helper)

	fmt.Fprintf(&b, "func %s(m map[string][]%s, field string, who %s) bool {\n", helper, pt, pt)
	b.WriteString("\tallow, restricted := m[field]\n")
	b.WriteString("\tif !restricted {\n\t\treturn true\n\t}\n")
	b.WriteString("\tfor _, a := range allow {\n\t\tif a == who {\n\t\t\treturn true\n\t\t}\n\t}\n")
	b.WriteString("\treturn false\n}\n")

	return b.String()
}

func (fa *FieldAccess) sliceLit(toks []string) string {
	parts := make([]string, len(toks))
	for i, t := range toks {
		parts[i] = fa.constName(t)
	}
	return "[]" + fa.principalType() + "{" + strings.Join(parts, ", ") + "}"
}

func (fa *FieldAccess) RenderTS() string {
	tn := fa.typeName()
	pt := fa.principalType()
	policy := tn + "FieldPolicy"

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by Demesne field-access (object %q). DO NOT EDIT.\n\n", fa.Object)

	lits := make([]string, len(fa.Principals))
	for i, p := range fa.Principals {
		lits[i] = fmt.Sprintf("%q", p)
	}
	fmt.Fprintf(&b, "export type %s = %s;\n\n", pt, strings.Join(lits, " | "))

	fmt.Fprintf(&b, "export class %s {\n", policy)
	fmt.Fprintf(&b, "  private read = new Map<string, %s[]>();\n", pt)
	fmt.Fprintf(&b, "  private write = new Map<string, %s[]>();\n\n", pt)
	b.WriteString("  constructor() {\n")
	for _, r := range fa.Rules {
		if len(r.Read) > 0 {
			fmt.Fprintf(&b, "    this.read.set(%q, [%s]);\n", r.Field, fa.tsList(r.Read))
		}
		if len(r.Write) > 0 {
			fmt.Fprintf(&b, "    this.write.set(%q, [%s]);\n", r.Field, fa.tsList(r.Write))
		}
	}
	b.WriteString("  }\n\n")

	fmt.Fprintf(&b, "  setRead(field: string, ...who: %s[]): void { this.read.set(field, who); }\n", pt)
	fmt.Fprintf(&b, "  setWrite(field: string, ...who: %s[]): void { this.write.set(field, who); }\n\n", pt)

	fmt.Fprintf(&b, "  canReadField(field: string, who: %s): boolean { return fieldAllowed(this.read, field, who); }\n", pt)
	fmt.Fprintf(&b, "  canWriteField(field: string, who: %s): boolean { return fieldAllowed(this.write, field, who); }\n", pt)
	b.WriteString("}\n\n")

	b.WriteString("function fieldAllowed<T>(m: Map<string, T[]>, field: string, who: T): boolean {\n")
	b.WriteString("  const allow = m.get(field);\n")
	b.WriteString("  if (allow === undefined) return true;\n")
	b.WriteString("  return allow.includes(who);\n")
	b.WriteString("}\n")

	return b.String()
}

func (fa *FieldAccess) tsList(toks []string) string {
	parts := make([]string, len(toks))
	for i, t := range toks {
		parts[i] = fmt.Sprintf("%q", t)
	}
	return strings.Join(parts, ", ")
}

func (fa *FieldAccess) RenderGrants(table string) string {
	type grant struct {
		verb string
		col  string
		role string
	}
	var grants []grant
	for _, r := range fa.Rules {
		if r.Column == "" {
			continue
		}
		for _, role := range r.Read {
			grants = append(grants, grant{"SELECT", r.Column, role})
		}
		for _, role := range r.Write {
			grants = append(grants, grant{"UPDATE", r.Column, role})
		}
	}
	if len(grants) == 0 {
		return ""
	}
	sort.Slice(grants, func(i, j int) bool {
		if grants[i].col != grants[j].col {
			return grants[i].col < grants[j].col
		}
		if grants[i].verb != grants[j].verb {
			return grants[i].verb < grants[j].verb
		}
		return grants[i].role < grants[j].role
	})
	var b strings.Builder
	fmt.Fprintf(&b, "-- Code generated by Demesne field-access (object %q). DO NOT EDIT.\n", fa.Object)
	for _, g := range grants {
		fmt.Fprintf(&b, "GRANT %s (%s) ON %s TO %s;\n", g.verb, g.col, table, g.role)
	}
	return b.String()
}
