package demesne

import (
	"fmt"
	"strings"
)

// Claims-contract emitter (RFC §6.1). The topology + subjects own the JWT claims
// contract end-to-end; this renders it as a generated Go artifact (the canonical
// key set WithRLS / session minting must provide). Phase B has the live
// BuildRLSClaims consume this; Phase A's oracle asserts the live minting covers
// every key and no RLS predicate references a key outside it.

// RenderClaimsContractGo emits a deterministic, sorted Go declaration of the
// claims contract for the given var name.
func (s *Spec) RenderClaimsContractGo(varName string) (string, error) {
	keys, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Code generated by Demesne from the authorization spec. DO NOT EDIT.\n")
	b.WriteString("// The JWT claims contract: every scope column (per non-virtual topology\n")
	b.WriteString("// level) + every subject identity key. WithRLS / session minting must set\n")
	b.WriteString("// these; no RLS predicate may reference a key outside this set (V5).\n")
	fmt.Fprintf(&b, "var %s = []string{\n", varName)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q,\n", k)
	}
	b.WriteString("}\n")
	return b.String(), nil
}
