package demesne

import (
	"fmt"
	"sort"
	"strings"
)

func (s *Spec) EmitFrameworkTS() (string, error) {
	contract, err := s.ClaimsContract()
	if err != nil {
		return "", err
	}
	surf, err := s.EmitAppSurface()
	if err != nil {
		return "", err
	}

	g := &fwTSGen{spec: s}
	g.claims(contract)
	g.querier()
	g.banner(s.compositePKObjects())
	g.pdpBanner(s.orphanPDPVerbs())
	for _, o := range surf.Objects {
		obj := s.objectByName(o.Object)
		if obj == nil {
			continue
		}
		g.object(o, obj)
	}
	for _, rs := range s.RoleStores {
		suffix := ""
		if len(s.RoleStores) > 1 {
			suffix = goExport(rs.Name)
		}
		if err := g.holds(rs, suffix); err != nil {
			return "", err
		}
	}
	g.checkFunc()
	g.checkHandler()

	return g.assemble(), nil
}

type fwTSGen struct {
	spec   *Spec
	b      strings.Builder
	checks []fwTSCheck

	needCompose bool
	needResolve bool
	needEff     bool
	needHolds   bool
	needRA      bool
}

type fwTSCheck struct{ object, verb, method string }

func (g *fwTSGen) assemble() string {
	var head strings.Builder
	head.WriteString("// Code generated by Demesne. DO NOT EDIT.\n\n")

	values := []string{"Decision", "mintClaimsValuesWithExtra"}
	if g.needCompose {
		values = append(values, "composeCan")
	}
	if g.needResolve {
		values = append(values, "resolve")
	}
	sort.Strings(values)
	fmt.Fprintf(&head, "import { %s } from \"@demesne/runtime\";\n", strings.Join(values, ", "))

	var types []string
	if g.needEff {
		types = append(types, "EffectivePerms")
	}
	if g.needHolds {
		types = append(types, "HoldsResolver")
	}
	if g.needRA {
		types = append(types, "RoleAssignment")
	}
	if len(types) > 0 {
		sort.Strings(types)
		fmt.Fprintf(&head, "import type { %s } from \"@demesne/runtime\";\n", strings.Join(types, ", "))
	}

	head.WriteString("\nexport { Decision };\n\n")
	return head.String() + g.b.String()
}

func (g *fwTSGen) claims(contract []string) {
	setting, _ := g.spec.claimSetting()
	role := g.spec.claimRole()

	fmt.Fprintf(&g.b, "export const claimsContract: string[] = %s;\n\n", tsJSON(strs(contract), false))

	g.b.WriteString("export interface Claims {\n")
	for _, k := range contract {
		fmt.Fprintf(&g.b, "  %s?: string;\n", unexport(k))
	}
	g.b.WriteString("  extra?: Record<string, string>;\n")
	g.b.WriteString("}\n\n")

	g.b.WriteString("export function mint(c: Claims): string {\n")
	g.b.WriteString("  const values: Record<string, string> = {};\n")
	for _, k := range contract {
		f := unexport(k)
		fmt.Fprintf(&g.b, "  if (c.%s !== undefined && c.%s !== \"\") values[%s] = c.%s;\n", f, f, tsStr(k), f)
	}
	g.b.WriteString("  return mintClaimsValuesWithExtra(claimsContract, values, c.extra);\n")
	g.b.WriteString("}\n\n")

	fmt.Fprintf(&g.b, "export const connectionRole = %s;\n", tsStr(role))
	fmt.Fprintf(&g.b, "export const claimsGUC = %s;\n\n", tsStr(setting))

	g.b.WriteString(`export function setRoleSQL(local: boolean): string {
  return (local ? "SET LOCAL ROLE " : "SET ROLE ") + connectionRole;
}

export function claimsSetSQL(local: boolean): string {
  return "SELECT set_config('" + claimsGUC + "', $1, " + (local ? "true" : "false") + ")";
}

export function sessionSetupSQL(local: boolean): [string, string] {
  return [setRoleSQL(local), claimsSetSQL(local)];
}

`)
}

func (g *fwTSGen) querier() {
	g.b.WriteString("export interface Querier {\n")
	g.b.WriteString("  query(text: string, params: unknown[]): Promise<{ rows: any[] }>;\n")
	g.b.WriteString("}\n\n")
}

func (g *fwTSGen) banner(skipped []*Object) {
	if len(skipped) == 0 {
		return
	}
	g.b.WriteString("// These objects declare a composite primary key — no single-column row identity, so no\n")
	g.b.WriteString("// can / listResources / checkMany is generated for them. Reach such rows via your own\n")
	g.b.WriteString("// predicate or a related object:\n")
	for _, o := range skipped {
		fmt.Fprintf(&g.b, "//   - %s (table %s, pk %s)\n", o.Name, o.Table, strings.Join(o.PKCols, ", "))
	}
	g.b.WriteString("\n")
}

func (g *fwTSGen) pdpBanner(orphan []string) {
	if len(orphan) == 0 {
		return
	}
	g.b.WriteString("// These @pdp verbs need a permission no rolestore vocabulary covers, so no holds\n")
	g.b.WriteString("// resolver is generated for them — resolve their held input yourself, or add a rolestore\n")
	g.b.WriteString("// for the permission's vocabulary:\n")
	for _, v := range orphan {
		fmt.Fprintf(&g.b, "//   - %s\n", v)
	}
	g.b.WriteString("\n")
}

func (g *fwTSGen) object(o AppObjectSurface, obj *Object) {
	name := unexport(o.Object)
	fmt.Fprintf(&g.b, "export const %s = {\n", name)

	first := true
	emit := func(s string) {
		if !first {
			g.b.WriteString("\n")
		}
		first = false
		g.b.WriteString(s)
	}

	for _, pm := range obj.Perms {
		method := "can" + goExport(pm.Verb)
		switch {
		case containsStr(pm.Layers, "pdp"):
			g.needEff = true
			emit(g.pdpCanTS(method, pm))
		case pm.Maps == "select":
			g.needCompose = true
			emit(g.rowCanTS(method, o.CheckSQL()))
			g.checks = append(g.checks, fwTSCheck{o.Object, pm.Verb, name + "." + method})
		case pm.Maps == "update":
			if o.EditCheckSQL == "" {
				continue
			}
			g.needCompose = true
			emit(g.rowCanTS(method, o.EditCheckSQL))
			g.checks = append(g.checks, fwTSCheck{o.Object, pm.Verb, name + "." + method})
		}
	}

	listSQL := o.ListResourcesSQL()
	if o.FlatListFn != "" {
		listSQL = o.ListResourcesFastSQL()
	}
	emit(g.listTS(listSQL, o.PK))
	emit(g.checkManyTS(o.CheckManySQL(), o.PK))

	g.b.WriteString("};\n\n")
}

func (g *fwTSGen) rowCanTS(method, sql string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "  async %s(q: Querier, id: string): Promise<Decision> {\n", method)
	fmt.Fprintf(&b, "    const { rows } = await q.query(%s, [id]);\n", tsStr(sql))
	b.WriteString("    return composeCan(true, Boolean(rows[0]?.exists), Decision.NotGoverned);\n")
	b.WriteString("  },\n")
	return b.String()
}

func (g *fwTSGen) pdpCanTS(method string, pm *Perm) string {
	var b strings.Builder
	fmt.Fprintf(&b, "  %s(held: EffectivePerms): Decision {\n", method)
	for _, t := range pm.Expr {
		if t.Ident != "" {
			fmt.Fprintf(&b, "    if (!held.holds(%s)) return Decision.Deny;\n", tsStr(t.Ident))
		}
	}
	b.WriteString("    return Decision.Allow;\n")
	b.WriteString("  },\n")
	return b.String()
}

func (g *fwTSGen) listTS(sql, pk string) string {
	var b strings.Builder
	b.WriteString("  async listResources(q: Querier, after: string | null, limit: number): Promise<string[]> {\n")
	fmt.Fprintf(&b, "    const { rows } = await q.query(%s, [after, limit]);\n", tsStr(sql))
	fmt.Fprintf(&b, "    return rows.map((r) => r[%s] as string);\n", tsStr(pk))
	b.WriteString("  },\n")
	return b.String()
}

func (g *fwTSGen) checkManyTS(sql, pk string) string {
	var b strings.Builder
	b.WriteString("  async checkMany(q: Querier, ids: string[]): Promise<string[]> {\n")
	fmt.Fprintf(&b, "    const { rows } = await q.query(%s, [ids]);\n", tsStr(sql))
	fmt.Fprintf(&b, "    return rows.map((r) => r[%s] as string);\n", tsStr(pk))
	b.WriteString("  },\n")
	return b.String()
}

func (g *fwTSGen) holds(rs *RoleStore, suffix string) error {
	r, err := g.spec.HoldsResolver(rs.Name)
	if err != nil {
		return err
	}
	g.needResolve = true
	g.needEff = true
	g.needHolds = true
	g.needRA = true

	fmt.Fprintf(&g.b, "export const holdsResolver%s: HoldsResolver = %s;\n\n", suffix, tsJSON(tsHolds(r), true))
	fmt.Fprintf(&g.b, "export const assignmentsSQL%s = %s;\n\n", suffix, tsStr(r.AssignmentsSQL()))

	fmt.Fprintf(&g.b, "export function resolveHeld%s(assignments: RoleAssignment[], scope: string[]): EffectivePerms {\n", suffix)
	fmt.Fprintf(&g.b, "  return resolve(holdsResolver%s, assignments, scope);\n", suffix)
	g.b.WriteString("}\n\n")

	fmt.Fprintf(&g.b, "export async function holds%s(q: Querier, principalId: string, scope: string[]): Promise<EffectivePerms> {\n", suffix)
	fmt.Fprintf(&g.b, "  const { rows } = await q.query(assignmentsSQL%s, [principalId]);\n", suffix)
	g.b.WriteString("  const assignments: RoleAssignment[] = rows.map((row) => ({\n")
	fmt.Fprintf(&g.b, "    scope: holdsResolver%s.scopeCols.map((c) => String(row[c])),\n", suffix)
	fmt.Fprintf(&g.b, "    roleKey: String(row[holdsResolver%s.keyCol]),\n", suffix)
	fmt.Fprintf(&g.b, "    permissions: holdsResolver%s.permsCol !== \"\" ? (row[holdsResolver%s.permsCol] as string[]) : [],\n", suffix, suffix)
	g.b.WriteString("  }));\n")
	fmt.Fprintf(&g.b, "  return resolveHeld%s(assignments, scope);\n", suffix)
	g.b.WriteString("}\n\n")
	return nil
}

func (g *fwTSGen) checkFunc() {
	g.b.WriteString("export async function check(q: Querier, object: string, verb: string, id: string): Promise<Decision> {\n")
	g.b.WriteString("  switch (object + \".\" + verb) {\n")
	for _, c := range g.checks {
		fmt.Fprintf(&g.b, "    case %s:\n      return %s(q, id);\n", tsStr(c.object+"."+c.verb), c.method)
	}
	g.b.WriteString("    default:\n      return Decision.NotGoverned;\n  }\n}\n\n")
}

func (g *fwTSGen) checkHandler() {
	g.b.WriteString(`export function checkHandler(q: Querier): (req: Request) => Promise<Response> {
  return async (req: Request): Promise<Response> => {
    const url = new URL(req.url);
    try {
      const d = await check(
        q,
        url.searchParams.get("object") ?? "",
        url.searchParams.get("verb") ?? "",
        url.searchParams.get("id") ?? "",
      );
      return new Response(JSON.stringify({ decision: d }), {
        headers: { "Content-Type": "application/json" },
      });
    } catch (e) {
      return new Response((e as Error).message, { status: 500 });
    }
  };
}
`)
}

func tsStr(s string) string { return tsJSON(s, false) }
