package demesne

import (
	"fmt"
	"sort"
	"strings"
)

type PDP struct {
	EmitSite   string
	Policy     map[string]string
	Ungoverned map[string]string
}

func (s *Spec) EmitPDP() (map[string]*PDP, error) {
	vocabPerms := map[string]map[string]bool{}
	for _, v := range s.Vocabs {
		set := map[string]bool{}
		for _, p := range v.Permissions {
			set[p] = true
		}
		vocabPerms[v.Name] = set
	}

	out := map[string]*PDP{}
	site := func(name string) *PDP {
		if out[name] == nil {
			out[name] = &PDP{EmitSite: name, Policy: map[string]string{}, Ungoverned: map[string]string{}}
		}
		return out[name]
	}

	var errs []string
	for _, pr := range s.Procedures {
		if _, ok := vocabPerms[pr.EmitSite]; !ok {
			errs = append(errs, fmt.Sprintf("line %d: procedures block targets unknown vocabulary %q (V10)", pr.Pos.Line, pr.EmitSite))
			continue
		}
		p := site(pr.EmitSite)
		for _, e := range pr.Entries {
			if !vocabPerms[pr.EmitSite][e.Perm] {
				errs = append(errs, fmt.Sprintf("line %d: %s -> %s: permission not in vocabulary %q", e.Pos.Line, e.Proc, e.Perm, pr.EmitSite))
			}
			if prev, dup := p.Policy[e.Proc]; dup && prev != e.Perm {
				errs = append(errs, fmt.Sprintf("line %d: procedure %s mapped to both %s and %s", e.Pos.Line, e.Proc, prev, e.Perm))
			}
			p.Policy[e.Proc] = e.Perm
		}
	}
	for _, u := range s.Ungoverned {
		if _, ok := vocabPerms[u.EmitSite]; !ok {
			errs = append(errs, fmt.Sprintf("line %d: ungoverned block targets unknown vocabulary %q (V10)", u.Pos.Line, u.EmitSite))
			continue
		}
		p := site(u.EmitSite)
		for _, e := range u.Entries {
			if _, gov := p.Policy[e.Proc]; gov {
				errs = append(errs, fmt.Sprintf("line %d: procedure %s is both governed and ungoverned", e.Pos.Line, e.Proc))
			}
			p.Ungoverned[e.Proc] = e.Reason
		}
	}
	if len(errs) > 0 {
		return nil, fmt.Errorf("PDP emit:\n  %s", strings.Join(errs, "\n  "))
	}
	return out, nil
}

func (s *Spec) EmitFieldScopes() (map[string]map[string]string, error) {
	out := map[string]map[string]string{}
	var errs []string
	for _, fs := range s.FieldScopes {
		m := out[fs.Site]
		if m == nil {
			m = map[string]string{}
			out[fs.Site] = m
		}
		for _, e := range fs.Entries {
			if prev, dup := m[e.Field]; dup && prev != e.Scope {
				errs = append(errs, fmt.Sprintf("line %d: field %q mapped to both %s and %s", e.Pos.Line, e.Field, prev, e.Scope))
			}
			m[e.Field] = e.Scope
		}
	}
	if len(errs) > 0 {
		return nil, fmt.Errorf("field-scopes emit:\n  %s", strings.Join(errs, "\n  "))
	}
	return out, nil
}

func (p *PDP) RenderGo(varName string) string {
	procs := make([]string, 0, len(p.Policy))
	for k := range p.Policy {
		procs = append(procs, k)
	}
	sort.Strings(procs)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by Demesne from the %q emit-site. DO NOT EDIT.\n", p.EmitSite)
	fmt.Fprintf(&b, "var %s = map[string]string{\n", varName)
	for _, proc := range procs {
		fmt.Fprintf(&b, "\t%q: %q,\n", proc, p.Policy[proc])
	}
	b.WriteString("}\n")
	return b.String()
}
