package demesne

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Generates the TypeScript worked example's two engine artifacts from
// examples/roundtrip.demesne — the projection module (EmitTS) and the DDL the example
// applies to a real Postgres (definers + enablement + RLS, the emitAllSQL order). They
// are committed under ts/packages/example-app/generated/ for the round-trip test to
// import/apply; this golden test keeps them in lockstep with the engine.
//
// Regenerate after an intentional change:  UPDATE_ORACLE=1 go test -run TestRoundtrip_Fixtures

func roundtripDDL(s *Spec) (string, error) {
	defs, err := s.EmitDefiners()
	if err != nil {
		return "", err
	}
	rls, err := s.EmitRLS()
	if err != nil {
		return "", err
	}
	if len(rls.Unsupported) > 0 {
		return "", &emitErr{strings.Join(rls.Unsupported, "; ")}
	}
	var b strings.Builder
	b.WriteString("-- Code generated by Demesne from examples/roundtrip.demesne. DO NOT EDIT.\n\n")
	b.WriteString(DefinersSQL(defs))
	b.WriteString("\n")
	b.WriteString(rls.EnablementSQL())
	b.WriteString("\n")
	b.WriteString(rls.PolicySQL("authenticated"))
	if !strings.HasSuffix(b.String(), "\n") {
		b.WriteString("\n")
	}
	return b.String(), nil
}

type emitErr struct{ s string }

func (e *emitErr) Error() string { return "uncompilable @rls permissions: " + e.s }

func TestRoundtrip_Fixtures(t *testing.T) {
	src, err := os.ReadFile(filepath.Join("examples", "roundtrip.demesne"))
	if err != nil {
		t.Fatalf("read spec: %v", err)
	}
	s, err := Parse(string(src))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if err := Validate(s); err != nil {
		t.Fatalf("validate: %v", err)
	}

	proj, err := s.EmitTS()
	if err != nil {
		t.Fatalf("EmitTS: %v", err)
	}
	ddl, err := roundtripDDL(s)
	if err != nil {
		t.Fatalf("roundtripDDL: %v", err)
	}

	dir := filepath.Join("ts", "packages", "example-app", "generated")
	artifacts := map[string]string{
		"projection.ts": proj,
		"policies.sql":  ddl,
	}
	update := os.Getenv("UPDATE_ORACLE") != ""
	if update {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	for name, want := range artifacts {
		path := filepath.Join(dir, name)
		if update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			t.Logf("wrote %s", path)
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("%s missing — run: UPDATE_ORACLE=1 go test -run TestRoundtrip_Fixtures", path)
		}
		if !bytes.Equal(got, []byte(want)) {
			t.Errorf("%s out of date — run: UPDATE_ORACLE=1 go test -run TestRoundtrip_Fixtures", path)
		}
	}
}
