// Code generated by Demesne from the authorization spec. DO NOT EDIT.
//
// The typed app surface: Claims + session, per-object Can<Verb>, scoped query
// builders, the holds-resolver, a reusable Check, and an HTTP check endpoint. Imports
// the demesne engine for the shared composition rules; everything runs under the
// caller's claims so the DB decides. Adapt a connection with demesne.FromSQL
// (database/sql) or github.com/eidestudio/demesne/pgx.FromPgx (pgx).

package supabaseauthz

import (
	"context"
	"encoding/json"
	"net/http"

	demesne "github.com/eidestudio/demesne"
)

// Decision is the engine's authorization decision tri-state, re-exported so callers
// need not import the engine directly.
type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

// claimsContract is the spec's claim key set (byte-sorted) — the keys Claims mints.
var claimsContract = []string{"member_ref", "org", "ws"}

// Claims is the typed claims contract — one field per key. A zero-value field is
// omitted from the minted blob. Extra carries deployment-specific, NON-contract
// claims (a derived discriminator, a secrets-DB key) the spec does not model; they
// are merged in without contract validation (EID-371 §4.3).
type Claims struct {
	MemberRef string
	Org       string
	Ws        string
	Extra     map[string]string
}

func (c Claims) values() map[string]string {
	m := map[string]string{}
	if c.MemberRef != "" {
		m["member_ref"] = c.MemberRef
	}
	if c.Org != "" {
		m["org"] = c.Org
	}
	if c.Ws != "" {
		m["ws"] = c.Ws
	}
	return m
}

// Mint renders the deterministic claims blob (sorted keys) to install in the GUC.
func (c Claims) Mint() (string, error) {
	return demesne.MintClaimsValuesWithExtra(claimsContract, c.values(), c.Extra)
}

// The RLS connection role + claims GUC the session assumes (spec-declared, defaulted).
const ConnectionRole = "authenticated"
const claimsGUC = "request.jwt.claims"

// SetRoleSQL assumes the RLS connection role so policies evaluate; local scopes it to
// the current transaction.
func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

// ClaimsSetSQL installs the minted claims blob ($1) into the GUC the policies read.
func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

// SessionSetupSQL is the WithRLS envelope: assume the role, then install the claims. Run in
// order at the top of an RLS transaction; the SECOND statement binds the Mint() result to $1.
func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

// Note is the typed access surface for the "note" object (table notes, pk note_pk).
type noteAccess struct{}

var Note = noteAccess{}

// CanView reports whether the caller can SEE the note row (its read policy). Run under the caller's claims + RLS role.
func (noteAccess) CanView(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM notes WHERE note_pk = $1)", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

// ListResources returns a keyset page of the note rows the caller can SEE.
// after is the last PK of the previous page (nil for the first); limit is the page size.
func (noteAccess) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT note_pk FROM notes WHERE ($1::text IS NULL OR note_pk::text > $1::text) ORDER BY note_pk::text LIMIT $2", after, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// CheckMany returns the subset of ids the caller can SEE (one round-trip).
func (noteAccess) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT note_pk FROM notes WHERE note_pk = ANY($1)", ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// Check dispatches a row read/edit check by object + verb (the dynamic, transport-free
// surface). An unknown object/verb returns NotGoverned. @pdp verbs are not dispatchable
// by id — use the typed Can<Verb>(held) + Holds.
func Check(ctx context.Context, q demesne.Querier, object, verb, id string) (Decision, error) {
	switch object + "." + verb {
	case "note.view":
		return Note.CanView(ctx, q, id)
	default:
		return NotGoverned, nil
	}
}

// CheckHandler answers the app-level read/edit check over Check:
//
//	?object=<o>&verb=<v>&id=<id>  ->  {"decision":"allow|deny|ungoverned"}
//
// Pass a Querier already bound to the request's session (role + claims set).
func CheckHandler(q demesne.Querier) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		d, err := Check(r.Context(), q, r.FormValue("object"), r.FormValue("verb"), r.FormValue("id"))
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]string{"decision": d.String()})
	}
}
