// Code generated by Demesne. DO NOT EDIT.

package supabaseauthz

import (
	"context"
	"encoding/json"
	"net/http"

	demesne "github.com/foir-io/demesne"
)

type Decision = demesne.Decision

const (
	Allow       = demesne.Allow
	Deny        = demesne.Deny
	NotGoverned = demesne.NotGoverned
)

var claimsContract = []string{"member_ref", "org", "ws"}

type Claims struct {
	MemberRef string
	Org       string
	Ws        string
	Extra     map[string]string
}

func (c Claims) values() map[string]string {
	m := map[string]string{}
	if c.MemberRef != "" {
		m["member_ref"] = c.MemberRef
	}
	if c.Org != "" {
		m["org"] = c.Org
	}
	if c.Ws != "" {
		m["ws"] = c.Ws
	}
	return m
}

func (c Claims) Mint() (string, error) {
	return demesne.MintClaimsValuesWithExtra(claimsContract, c.values(), c.Extra)
}

const ConnectionRole = "authenticated"
const claimsGUC = "request.jwt.claims"

func SetRoleSQL(local bool) string {
	if local {
		return "SET LOCAL ROLE " + ConnectionRole
	}
	return "SET ROLE " + ConnectionRole
}

func ClaimsSetSQL(local bool) string {
	if local {
		return "SELECT set_config('" + claimsGUC + "', $1, true)"
	}
	return "SELECT set_config('" + claimsGUC + "', $1, false)"
}

func SessionSetupSQL(local bool) []string {
	return []string{SetRoleSQL(local), ClaimsSetSQL(local)}
}

type noteAccess struct{}

var Note = noteAccess{}

func (noteAccess) CanView(ctx context.Context, q demesne.Querier, id string) (Decision, error) {
	var ok bool
	if err := q.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM notes WHERE note_pk = $1)", id).Scan(&ok); err != nil {
		return Deny, err
	}
	return demesne.ComposeCan(true, ok, demesne.NotGoverned), nil
}

func (noteAccess) ListResources(ctx context.Context, q demesne.Querier, after *string, limit int) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT note_pk FROM notes WHERE ($1::text IS NULL OR note_pk::text > $1::text) ORDER BY note_pk::text LIMIT $2", after, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

func (noteAccess) CheckMany(ctx context.Context, q demesne.Querier, ids []string) ([]string, error) {
	rows, err := q.QueryContext(ctx, "SELECT note_pk FROM notes WHERE note_pk = ANY($1)", ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

func Check(ctx context.Context, q demesne.Querier, object, verb, id string) (Decision, error) {
	switch object + "." + verb {
	case "note.view":
		return Note.CanView(ctx, q, id)
	default:
		return NotGoverned, nil
	}
}

func CheckHandler(q demesne.Querier) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		d, err := Check(r.Context(), q, r.FormValue("object"), r.FormValue("verb"), r.FormValue("id"))
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]string{"decision": d.String()})
	}
}
